# Generated by Django 5.2.14 on 2026-07-02 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0011_volunteer_consent_policy_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('security_fire', 'Security & Fire'), ('hvac', 'HVAC'), ('compliance_legal', 'Compliance & Legal'), ('utilities', 'Utilities'), ('property', 'Property'), ('digital_av', 'Digital & AV'), ('other', 'Other')], default='other', max_length=32)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('biannual', 'Twice a year'), ('annual', 'Annual'), ('three_yearly', 'Every 3 years'), ('bespoke', 'Bespoke / other')], default='annual', max_length=16)),
                ('frequency_notes', models.CharField(blank=True, default='', help_text='For bespoke or unusual patterns.', max_length=128)),
                ('contractor', models.CharField(blank=True, default='', help_text='Name of service provider if external; blank for volunteer-delivered tasks.', max_length=128)),
                ('keyholder_required', models.BooleanField(default=False)),
                ('skills_required', models.TextField(blank=True, default='', help_text='What you need to know or be trained in.')),
                ('time_commitment', models.CharField(blank=True, default='', help_text="e.g. '~2 hours', 'Half a day including travel'.", max_length=128)),
                ('nextcloud_link', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True, help_text='Retire tasks without losing history.')),
                ('committed_on', models.DateField(blank=True, null=True)),
                ('committed_to', models.ForeignKey(blank=True, help_text="Who has said they'll do the next occurrence, if anyone.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_maintenance_tasks', to='members.volunteer')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField()),
                ('completed_by_name', models.CharField(blank=True, default='', help_text='For contractor completions or cases where no toolkit account exists.', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('next_due_override', models.DateField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_maintenance_records', to='members.volunteer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='operations.maintenancetask')),
            ],
            options={
                'ordering': ['-completed_date'],
            },
        ),
    ]
