# Generated by Django 5.2.14 on 2026-06-28 12:22

import django.db.models.deletion
import toolkit.diary.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("labs", "0001_initial"),
        ("labs", "0002_donation_items_jobs"),
        ("labs", "0003_job_overhaul_donation_internal"),
        ("labs", "0004_collective_model"),
        ("labs", "0005_collective_audit_fields"),
        ("labs", "0006_collective_colour"),
        ("labs", "0007_collective_colour_free"),
        ("labs", "0008_loftitem_loftitemphoto"),
        ("labs", "0009_areaphoto"),
        ("labs", "0010_collectivelink"),
        ("labs", "0011_collective_invite_only"),
        ("labs", "0012_bulletin"),
        ("labs", "0013_collective_public_fields"),
        ("labs", "0014_alter_collective_listed_publicly"),
    ]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomNote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.CharField(max_length=100, unique=True)),
                ("body", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "labs_room_notes",
            },
        ),
        migrations.CreateModel(
            name="DonationItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("wanted", "Wanted"),
                            ("check_first", "Check first"),
                            ("not_needed", "Not needed"),
                        ],
                        default="wanted",
                        max_length=16,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Public-facing notes shown on the donations page.",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact for this item — leave blank to use the site default.",
                        max_length=128,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "internal_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes visible only to volunteers (e.g. storage location, condition requirements).",
                    ),
                ),
                (
                    "last_edited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "labs_donation_items",
                "ordering": ["category", "display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full description of the issue or task.",
                    ),
                ),
                ("keyholder_required", models.BooleanField(default=False)),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("high", "Urgent"),
                            ("medium", "Soon"),
                            ("low", "Whenever"),
                        ],
                        default="low",
                        max_length=16,
                    ),
                ),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posted_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Area or location, e.g. 'Kitchen', 'Roof', 'Anywhere'.",
                        max_length=128,
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("building", "In building"),
                            ("remote", "Remote"),
                            ("both", "Both"),
                        ],
                        default="building",
                        help_text="Can this be done remotely, or does it require being in the building?",
                        max_length=16,
                    ),
                ),
                (
                    "plan_status",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Current plan or status update.",
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the person who reported the issue and can provide more detail.",
                        max_length=128,
                    ),
                ),
                (
                    "safety_risk",
                    models.BooleanField(
                        default=False,
                        help_text="Is there an immediate safety risk?",
                    ),
                ),
                (
                    "skill_needed",
                    models.BooleanField(
                        default=False,
                        help_text="Does this require a specific skill or trade?",
                    ),
                ),
            ],
            options={
                "db_table": "labs_jobs",
            },
        ),
        migrations.CreateModel(
            name="Collective",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first."
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "volunteer_count",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Descriptive volunteer count shown on the collectives page.",
                        max_length=256,
                    ),
                ),
                ("about", models.TextField(blank=True, default="")),
                (
                    "roles",
                    models.TextField(
                        blank=True, default="", verbose_name="Roles and tasks"
                    ),
                ),
                (
                    "organising",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="How they meet and organise",
                    ),
                ),
                (
                    "proud_of",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="What they're most proud of",
                    ),
                ),
                (
                    "get_involved",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="How to get involved",
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact email or address shown at the bottom of the card.",
                        max_length=256,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("colour", models.CharField(default="#343a40", max_length=7)),
                (
                    "invite_only",
                    models.BooleanField(
                        default=False,
                        help_text="If set, volunteers cannot self-join — membership is managed by admins only.",
                    ),
                ),
                (
                    "listed_publicly",
                    models.BooleanField(
                        default=False,
                        help_text="Include this collective on the public /labs/collectives/public/ page. Requires public_copy to be set.",
                    ),
                ),
                (
                    "public_copy",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Short description for the public directory (100–300 characters). Leave blank to exclude from the public page even if listed_publicly is checked.",
                        verbose_name="Public description",
                    ),
                ),
            ],
            options={
                "db_table": "labs_collectives",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LoftItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loft_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "labs_loft_items",
                "ordering": ["zone_id", "added_at"],
            },
        ),
        migrations.CreateModel(
            name="LoftItemPhoto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="loft-photos/")),
                (
                    "caption",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="labs.loftitem",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "labs_loft_item_photos",
                "ordering": ["uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="AreaPhoto",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_id", models.CharField(max_length=100, unique=True)),
                ("image", models.ImageField(upload_to="area-photos/")),
                (
                    "caption",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "labs_area_photos",
            },
        ),
        migrations.CreateModel(
            name="CollectiveLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short name shown on the link chip, e.g. 'WhatsApp group' or 'Linktree'.",
                        max_length=80,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=500,
                        validators=[
                            toolkit.diary.validators.validate_event_link_url
                        ],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "collective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="labs.collective",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Bulletin",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank to use the site default (bulletin_default_expiry_days). Set explicitly to override.",
                        null=True,
                    ),
                ),
                (
                    "pinned",
                    models.BooleanField(
                        default=False,
                        help_text="Pinned bulletins appear at the top of the board regardless of date. Programmer+ only.",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "labs_bulletins",
                "ordering": ["-pinned", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulletinRead",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bulletin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reads",
                        to="labs.bulletin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "labs_bulletin_reads",
                "unique_together": {("bulletin", "user")},
            },
        ),
    ]
