# Generated by Django 5.2.13 on 2026-05-06 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_donation_items_jobs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='done',
            new_name='resolved',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='done_at',
            new_name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skills',
        ),
        migrations.AddField(
            model_name='donationitem',
            name='internal_notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes visible only to volunteers (e.g. storage location, condition requirements).'),
        ),
        migrations.AddField(
            model_name='donationitem',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='area',
            field=models.CharField(blank=True, default='', help_text="Area or location, e.g. 'Kitchen', 'Roof', 'Anywhere'.", max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='location_type',
            field=models.CharField(choices=[('building', 'In building'), ('remote', 'Remote'), ('both', 'Both')], default='building', help_text='Can this be done remotely, or does it require being in the building?', max_length=16),
        ),
        migrations.AddField(
            model_name='job',
            name='plan_status',
            field=models.TextField(blank=True, default='', help_text='Current plan or status update.'),
        ),
        migrations.AddField(
            model_name='job',
            name='reporter_name',
            field=models.CharField(blank=True, default='', help_text='Name of the person who reported the issue and can provide more detail.', max_length=128),
        ),
        migrations.AddField(
            model_name='job',
            name='safety_risk',
            field=models.BooleanField(default=False, help_text='Is there an immediate safety risk?'),
        ),
        migrations.AddField(
            model_name='job',
            name='skill_needed',
            field=models.BooleanField(default=False, help_text='Does this require a specific skill or trade?'),
        ),
        migrations.AlterField(
            model_name='donationitem',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Public-facing notes shown on the donations page.'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Full description of the issue or task.'),
        ),
    ]
