# Generated by Django 5.2.13 on 2026-05-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_job_overhaul_donation_internal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
                ('active', models.BooleanField(default=True)),
                ('volunteer_count', models.CharField(blank=True, default='', help_text='Descriptive volunteer count shown on the collectives page.', max_length=256)),
                ('about', models.TextField(blank=True, default='')),
                ('roles', models.TextField(blank=True, default='', verbose_name='Roles and tasks')),
                ('organising', models.TextField(blank=True, default='', verbose_name='How they meet and organise')),
                ('proud_of', models.TextField(blank=True, default='', verbose_name="What they're most proud of")),
                ('get_involved', models.TextField(blank=True, default='', verbose_name='How to get involved')),
                ('contact', models.CharField(blank=True, default='', help_text='Contact email or address shown at the bottom of the card.', max_length=256)),
            ],
            options={
                'db_table': 'labs_collectives',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
