# Generated by Django 5.2.14 on 2026-05-21 10:15

import django.db.models.deletion
import toolkit.diary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_areaphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Short name shown on the link chip, e.g. 'WhatsApp group' or 'Linktree'.", max_length=80)),
                ('url', models.URLField(max_length=500, validators=[toolkit.diary.validators.validate_event_link_url])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='labs.collective')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
