# Generated by Django 5.2.14 on 2026-05-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0010_collectivelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='invite_only',
            field=models.BooleanField(default=False, help_text='If set, volunteers cannot self-join — membership is managed by admins only.'),
        ),
    ]
