# Generated by Django 5.2.14 on 2026-05-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0012_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='listed_publicly',
            field=models.BooleanField(default=False, help_text='Include this collective on the public /collectives/ page. Requires public_copy to be set.'),
        ),
        migrations.AddField(
            model_name='collective',
            name='public_copy',
            field=models.TextField(blank=True, default='', help_text='Short description for the public directory (100–300 characters). Leave blank to exclude from the public page even if listed_publicly is checked.', verbose_name='Public description'),
        ),
    ]
