# Generated by Django 5.2.14 on 2026-05-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0013_collective_public_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collective',
            name='listed_publicly',
            field=models.BooleanField(default=False, help_text='Include this collective on the public /labs/collectives/public/ page. Requires public_copy to be set.'),
        ),
    ]
