# Generated by Django 5.2.14 on 2026-06-28 12:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_suppliers_from_records(apps, schema_editor):
    SupplierRecord = apps.get_model("labs", "SupplierRecord")
    Supplier = apps.get_model("labs", "Supplier")
    Volunteer = apps.get_model("members", "Volunteer")

    seen = {}
    for record in SupplierRecord.objects.filter(
        supplier_name__gt=""
    ).select_related():
        name = record.supplier_name.strip()
        if not name:
            continue
        if name not in seen:
            supplier, _ = Supplier.objects.get_or_create(name=name)
            # lift account_holder to Supplier on first encounter
            if record.account_holder_id and supplier.account_holder_id is None:
                supplier.account_holder_id = record.account_holder_id
                supplier.save()
            seen[name] = supplier
        record.supplier = seen[name]
        record.save()


def reverse_migration(apps, schema_editor):
    SupplierRecord = apps.get_model("labs", "SupplierRecord")
    SupplierRecord.objects.update(supplier=None)


class Migration(migrations.Migration):

    replaces = [
        ("labs", "0015_shopping_list"),
        ("labs", "0016_alter_consumableitem_category"),
        ("labs", "0017_founditem"),
        ("labs", "0018_founditem_report_type_reporter_contact"),
        ("labs", "0019_exchange_item"),
        ("labs", "0020_exchangeitem_share_fields"),
        ("labs", "0021_exchangeitem_borrowed_by"),
        ("labs", "0022_exchangeitem_borrowed_by_name_missing_status"),
        ("labs", "0023_add_collective_sample_role"),
        ("labs", "0024_add_collective_role"),
        ("labs", "0025_exchangeitem_borrowed_by_contact"),
        ("labs", "0026_supplier_and_pledge_status"),
        ("labs", "0027_supplier_data_migration"),
    ]

    dependencies = [
        ("labs", "0001_initial_v2"),
        ("members", "0017_volunteer_digest_fields"),
        ("members", "0023_rename_qualification_grant_fields"),
        ("members", "0028_volunteer_suspension_reason"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumableItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("cleaning", "Cleaning"),
                            ("stationery", "Stationery"),
                            ("kitchen", "Kitchen"),
                            ("snacks", "Cinema Snacks"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "labs_consumable_items",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="NeedFlag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notes",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flagged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="flagged_needs",
                        to="members.volunteer",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="need_flags",
                        to="labs.consumableitem",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_flags",
                        to="members.volunteer",
                    ),
                ),
            ],
            options={
                "db_table": "labs_need_flags",
                "ordering": ["-flagged_at"],
            },
        ),
        migrations.CreateModel(
            name="FoundItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("location_found", models.CharField(max_length=100)),
                ("found_on", models.DateField(default=datetime.date.today)),
                ("logged_by", models.CharField(max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="lost-and-found/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unclaimed", "Unclaimed"),
                            ("claimed", "Claimed"),
                            ("disposed", "Disposed"),
                        ],
                        default="unclaimed",
                        max_length=12,
                    ),
                ),
                (
                    "claimed_by",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("claimed_on", models.DateField(blank=True, null=True)),
                ("disposed_on", models.DateField(blank=True, null=True)),
                (
                    "disposal_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("binned", "Binned"),
                            ("donated", "Donated"),
                            ("returned", "Returned to owner"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("found", "Found item"),
                            ("lost", "Lost report"),
                        ],
                        default="found",
                        max_length=8,
                    ),
                ),
                (
                    "reporter_contact",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Private contact details for the person who lost the item. Not shown in the list view.",
                    ),
                ),
            ],
            options={
                "db_table": "labs_found_items",
                "ordering": ["-found_on", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="collective",
            name="sample_role",
            field=models.TextField(
                blank=True,
                default="",
                help_text="A short, concrete example of what a member might actually do — shown to help people decide whether to join.",
                verbose_name="Sample role",
            ),
        ),
        migrations.CreateModel(
            name="CollectiveRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "time_commitment",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. '~3hrs/month', 'weekly Tuesday evenings'",
                        max_length=128,
                    ),
                ),
                (
                    "getting_started",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="First concrete step for someone interested in this role.",
                    ),
                ),
                (
                    "needs_volunteers",
                    models.BooleanField(
                        default=False,
                        help_text="Flag this role as actively seeking more people (shown as a badge).",
                    ),
                ),
                (
                    "open_to_new_volunteers",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck if this role is currently invite-only or full.",
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                (
                    "collective",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defined_roles",
                        to="labs.collective",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("lend", "🔧 Lend — borrow and return"),
                            ("give", "🎁 Give away — free to a good home"),
                            ("share", "🥔 Share — help yourself to some"),
                        ],
                        default="give",
                        max_length=8,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tools", "Tools"),
                            ("kitchen", "Kitchen"),
                            ("av", "AV & tech"),
                            ("clothing", "Clothing"),
                            ("books", "Books & media"),
                            ("garden", "Garden"),
                            ("furniture", "Furniture"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("attention", "Needs attention"),
                        ],
                        default="good",
                        max_length=16,
                    ),
                ),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("collective", "S+S collective"),
                            ("volunteer", "Volunteer"),
                        ],
                        default="volunteer",
                        max_length=16,
                    ),
                ),
                (
                    "location_notes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Where to collect or arrange pickup — e.g. 'Bring to the next event' or 'Ask at the bar'.",
                        max_length=256,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("on_loan", "On loan"),
                            ("claimed", "Claimed"),
                            ("all_gone", "All gone"),
                            ("missing", "Missing"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="available",
                        max_length=16,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Quirks, usage notes, or anything relevant to whoever borrows/takes it.",
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="exchange/"),
                ),
                ("active", models.BooleanField(default=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_volunteer",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only visible to logged-in users. Set when owner is a volunteer.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exchange_items",
                        to="members.volunteer",
                    ),
                ),
                (
                    "quantity",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="How much is there? e.g. 'about 10kg', '3 trays', 'a big bag'. Share listings only.",
                        max_length=64,
                    ),
                ),
                (
                    "available_until",
                    models.DateField(
                        blank=True,
                        help_text="Optional — show urgency. Useful for food that will go off. Share listings only.",
                        null=True,
                    ),
                ),
                (
                    "borrowed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "borrowed_by_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text name for verbal/in-person loans. Shown instead of username if set.",
                        max_length=128,
                    ),
                ),
                (
                    "borrowed_by_contact",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Contact details provided by the borrower — visible only to the person who posted the listing.",
                        max_length=256,
                    ),
                ),
            ],
            options={
                "db_table": "labs_exchange_items",
                "ordering": ["listing_type", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "fulfilment_type",
                    models.CharField(
                        choices=[
                            ("delivery", "Online order / delivery"),
                            ("pickup", "Pick up in person"),
                            ("either", "Either"),
                        ],
                        default="either",
                        max_length=20,
                    ),
                ),
                ("ordering_url", models.URLField(blank=True, default="")),
                ("ordering_notes", models.TextField(blank=True, default="")),
                ("active", models.BooleanField(default=True)),
                (
                    "account_holder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_logins",
                        to="members.volunteer",
                    ),
                ),
            ],
            options={
                "db_table": "labs_suppliers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProcurementPledge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pledged_at", models.DateTimeField(auto_now_add=True)),
                ("eta_date", models.DateField(blank=True, null=True)),
                (
                    "eta_notes",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'Friday cleaning club'",
                        max_length=200,
                    ),
                ),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "need_flag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pledge",
                        to="labs.needflag",
                    ),
                ),
                (
                    "pledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pledges",
                        to="members.volunteer",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pledged", "Pledged"),
                            ("ordered", "Ordered / in basket"),
                            ("oos", "Out of stock"),
                            ("fulfilled", "Fulfilled"),
                        ],
                        default="pledged",
                        max_length=16,
                    ),
                ),
                (
                    "status_notes",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "intended_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pledges",
                        to="labs.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "labs_procurement_pledges",
            },
        ),
        migrations.CreateModel(
            name="SupplierRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplier_name", models.CharField(max_length=100)),
                (
                    "product_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("product_url", models.URLField(blank=True, default="")),
                (
                    "unit_desc",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. '6-pack', '5L'",
                        max_length=200,
                    ),
                ),
                (
                    "approx_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("ordering_notes", models.TextField(blank=True, default="")),
                ("account_notes", models.TextField(blank=True, default="")),
                (
                    "account_holder",
                    models.ForeignKey(
                        blank=True,
                        help_text="Volunteer who holds the login for this supplier account.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_accounts",
                        to="members.volunteer",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="labs.consumableitem",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="labs.supplier",
                    ),
                ),
            ],
            options={
                "db_table": "labs_supplier_records",
                "ordering": ["supplier_name"],
            },
        ),
        migrations.RunPython(
            code=populate_suppliers_from_records,
            reverse_code=reverse_migration,
        ),
    ]
