# Generated by Django 5.2.14 on 2026-05-25 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0014_alter_collective_listed_publicly'),
        ('members', '0017_volunteer_digest_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumableItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('cleaning', 'Cleaning'), ('stationery', 'Stationery'), ('kitchen', 'Kitchen'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'labs_consumable_items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NeedFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flagged_needs', to='members.volunteer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='need_flags', to='labs.consumableitem')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to='members.volunteer')),
            ],
            options={
                'db_table': 'labs_need_flags',
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementPledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledged_at', models.DateTimeField(auto_now_add=True)),
                ('eta_date', models.DateField(blank=True, null=True)),
                ('eta_notes', models.CharField(blank=True, default='', help_text="e.g. 'Friday cleaning club'", max_length=200)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('need_flag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pledge', to='labs.needflag')),
                ('pledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges', to='members.volunteer')),
            ],
            options={
                'db_table': 'labs_procurement_pledges',
            },
        ),
        migrations.CreateModel(
            name='SupplierRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('product_code', models.CharField(blank=True, default='', max_length=100)),
                ('product_url', models.URLField(blank=True, default='')),
                ('unit_desc', models.CharField(blank=True, default='', help_text="e.g. '6-pack', '5L'", max_length=200)),
                ('approx_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('ordering_notes', models.TextField(blank=True, default='')),
                ('account_notes', models.TextField(blank=True, default='')),
                ('account_holder', models.ForeignKey(blank=True, help_text='Volunteer who holds the login for this supplier account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_accounts', to='members.volunteer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='labs.consumableitem')),
            ],
            options={
                'db_table': 'labs_supplier_records',
                'ordering': ['supplier_name'],
            },
        ),
    ]
