# Generated by Django 5.2.14 on 2026-05-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0015_shopping_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumableitem',
            name='category',
            field=models.CharField(choices=[('cleaning', 'Cleaning'), ('stationery', 'Stationery'), ('kitchen', 'Kitchen'), ('snacks', 'Cinema Snacks'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
