# Generated by Django 5.2.14 on 2026-06-01 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0018_founditem_report_type_reporter_contact'),
        ('members', '0023_rename_qualification_grant_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='founditem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('lend', '🔧 Lend — borrow and return'), ('give', '🎁 Give away — free to a good home')], default='give', max_length=8)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('tools', 'Tools'), ('kitchen', 'Kitchen'), ('av', 'AV & tech'), ('clothing', 'Clothing'), ('books', 'Books & media'), ('garden', 'Garden'), ('furniture', 'Furniture'), ('other', 'Other')], default='other', max_length=16)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('attention', 'Needs attention')], default='good', max_length=16)),
                ('owner_type', models.CharField(choices=[('collective', 'S+S collective'), ('volunteer', 'Volunteer')], default='volunteer', max_length=16)),
                ('location_notes', models.CharField(blank=True, default='', help_text="Where to collect or arrange pickup — e.g. 'Bring to the next event' or 'Ask at the bar'.", max_length=256)),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_loan', 'On loan'), ('claimed', 'Claimed'), ('withdrawn', 'Withdrawn')], default='available', max_length=16)),
                ('notes', models.TextField(blank=True, default='', help_text='Quirks, usage notes, or anything relevant to whoever borrows/takes it.')),
                ('image', models.ImageField(blank=True, upload_to='exchange/')),
                ('active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner_volunteer', models.ForeignKey(blank=True, help_text='Only visible to logged-in users. Set when owner is a volunteer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exchange_items', to='members.volunteer')),
            ],
            options={
                'db_table': 'labs_exchange_items',
                'ordering': ['listing_type', 'category', 'name'],
            },
        ),
    ]
