# Generated by Django 5.2.14 on 2026-06-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0022_exchangeitem_borrowed_by_name_missing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='sample_role',
            field=models.TextField(blank=True, default='', help_text='A short, concrete example of what a member might actually do — shown to help people decide whether to join.', verbose_name='Sample role'),
        ),
    ]
