# Generated by Django 5.2.14 on 2026-06-16 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0023_add_collective_sample_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectiveRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('time_commitment', models.CharField(blank=True, default='', help_text="e.g. '~3hrs/month', 'weekly Tuesday evenings'", max_length=128)),
                ('getting_started', models.TextField(blank=True, default='', help_text='First concrete step for someone interested in this role.')),
                ('needs_volunteers', models.BooleanField(default=False, help_text='Flag this role as actively seeking more people (shown as a badge).')),
                ('open_to_new_volunteers', models.BooleanField(default=True, help_text='Uncheck if this role is currently invite-only or full.')),
                ('display_order', models.IntegerField(default=0)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defined_roles', to='labs.collective')),
            ],
            options={
                'ordering': ['display_order', 'pk'],
            },
        ),
    ]
