# Generated by Django 5.2.14 on 2026-06-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0025_exchangeitem_borrowed_by_contact'),
        ('members', '0028_volunteer_suspension_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementpledge',
            name='status',
            field=models.CharField(choices=[('pledged', 'Pledged'), ('ordered', 'Ordered / in basket'), ('oos', 'Out of stock'), ('fulfilled', 'Fulfilled')], default='pledged', max_length=16),
        ),
        migrations.AddField(
            model_name='procurementpledge',
            name='status_notes',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fulfilment_type', models.CharField(choices=[('delivery', 'Online order / delivery'), ('pickup', 'Pick up in person'), ('either', 'Either')], default='either', max_length=20)),
                ('ordering_url', models.URLField(blank=True, default='')),
                ('ordering_notes', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('account_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_logins', to='members.volunteer')),
            ],
            options={
                'db_table': 'labs_suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='procurementpledge',
            name='intended_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pledges', to='labs.supplier'),
        ),
        migrations.AddField(
            model_name='supplierrecord',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='labs.supplier'),
        ),
    ]
