# Generated by Django 5.2.14 on 2026-06-28 13:06

import django.db.migrations.operations.special
import django.db.models.deletion
import toolkit.diary.validators
from django.conf import settings
from django.db import migrations, models

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# toolkit.diary.migrations.0014_eventtemplate_role_counts
# toolkit.diary.migrations.0019_site_configuration
# toolkit.diary.migrations.0029_siteconfiguration_calendar_slot_min_hour
# toolkit.diary.migrations.0032_roombooking
# toolkit.diary.migrations.0034_room_map_slugs

DEFAULT_FILMS_START_BANNER_TEXT = (
    "We don't show adverts or trailers, so please arrive promptly, as films "
    "start as soon as most people have arrived."
)


def _parse_images_start_date(value):
    if not value:
        return None
    import datetime

    try:
        return datetime.datetime.strptime(value, "%d %b %Y").date()
    except (ValueError, TypeError):
        return None


def copy_roles_to_through_model(apps, schema_editor):
    db = schema_editor.connection.alias
    EventTemplate = apps.get_model("diary", "EventTemplate")
    EventTemplateRole = apps.get_model("diary", "EventTemplateRole")
    # At this point the old `roles` M2M (EventTemplates_Roles) is still present,
    # so we can iterate via the historical model accessor.
    for template in (
        EventTemplate.objects.using(db).prefetch_related("roles").all()
    ):
        for role in template.roles.using(db).all():
            EventTemplateRole.objects.using(db).get_or_create(
                template=template, role=role, defaults={"count": 1}
            )


def seed_singleton(apps, schema_editor):
    SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
    SiteConfiguration.objects.update_or_create(
        pk=1,
        defaults={
            "films_start_on_time": getattr(
                settings, "FILMS_START_ON_TIME", False
            ),
            "films_start_on_time_banner_text": DEFAULT_FILMS_START_BANNER_TEXT,
            "rota_show_tags": getattr(settings, "ROTA_SHOW_TAGS", True),
            "rota_clear_email_prompt_enabled": getattr(
                settings, "ROTA_CLEAR_EMAIL_PROMPT_ENABLED", True
            ),
            "show_archive_images": getattr(
                settings, "SHOW_ARCHIVE_IMAGES", True
            ),
            "images_start_date": _parse_images_start_date(
                getattr(settings, "IMAGES_START_DATE", None)
            ),
            "max_count_per_role": getattr(settings, "MAX_COUNT_PER_ROLE", 8),
            "programme_copy_summary_max_chars": getattr(
                settings, "PROGRAMME_COPY_SUMMARY_MAX_CHARS", 450
            ),
            "programme_event_terms_min_words": getattr(
                settings, "PROGRAMME_EVENT_TERMS_MIN_WORDS", 3
            ),
            "programme_media_max_size_mb": getattr(
                settings, "PROGRAMME_MEDIA_MAX_SIZE_MB", 5
            ),
            "mailout_details_days_ahead": getattr(
                settings, "MAILOUT_DETAILS_DAYS_AHEAD", 9
            ),
            "mailout_listings_days_ahead": getattr(
                settings, "MAILOUT_LISTINGS_DAYS_AHEAD", 14
            ),
            "membership_length_days": getattr(
                settings, "MEMBERSHIP_LENGTH_DAYS", 365
            ),
            "default_training_expiry_months": getattr(
                settings, "DEFAULT_TRAINING_EXPIRY_MONTHS", 12
            ),
            "image_copyright_guidance_url": getattr(
                settings, "IMAGE_COPYRIGHT_GUIDANCE_URL", ""
            )
            or "",
            "alt_text_guidance_url": getattr(
                settings, "ALT_TEXT_GUIDANCE_URL", ""
            )
            or "",
        },
    )


def noop_reverse(apps, schema_editor):
    SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
    SiteConfiguration.objects.filter(pk=1).delete()


def _add_column(apps, schema_editor):
    # MySQL/MariaDB DDL is non-transactional: use IF NOT EXISTS so a crash
    # between the ALTER TABLE and the django_migrations INSERT doesn't leave
    # the column missing on the next startup. Other backends (SQLite in tests)
    # use standard schema_editor.add_field, which errors cleanly on duplicate.
    if schema_editor.connection.vendor == "mysql":
        schema_editor.execute(
            "ALTER TABLE SiteConfiguration "
            "ADD COLUMN IF NOT EXISTS calendar_slot_min_hour "
            "smallint(5) unsigned NOT NULL DEFAULT 10"
        )
    else:
        SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
        field = models.PositiveSmallIntegerField(default=10)
        field.set_attributes_from_name("calendar_slot_min_hour")
        with schema_editor.connection.schema_editor() as inner:
            inner.add_field(SiteConfiguration, field)


def _drop_column(apps, schema_editor):
    if schema_editor.connection.vendor == "mysql":
        schema_editor.execute(
            "ALTER TABLE SiteConfiguration DROP COLUMN IF EXISTS calendar_slot_min_hour"
        )
    else:
        SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
        field = models.PositiveSmallIntegerField(default=10)
        field.set_attributes_from_name("calendar_slot_min_hour")
        with schema_editor.connection.schema_editor() as inner:
            inner.remove_field(SiteConfiguration, field)


def backfill_room_bookings(apps, schema_editor):
    """For each Showing that had a room, create a single RoomBooking."""
    Showing = apps.get_model("diary", "Showing")
    RoomBooking = apps.get_model("diary", "RoomBooking")

    for showing in Showing.objects.filter(room__isnull=False).select_related(
        "event", "room"
    ):
        duration = showing.event.duration
        if duration is not None:
            import datetime

            end = showing.start + datetime.timedelta(
                hours=duration.hour, minutes=duration.minute
            )
        else:
            end = None
        RoomBooking.objects.create(
            showing=showing,
            room=showing.room,
            start=showing.start,
            end=end,
            notes="",
        )


ROOM_SLUGS = {
    "Cinema": "room-cinema",
    "Venue Space": "room-venue",
    "Café": "room-cafe",
    "Meeting": "room-meeting-room",
    "Dark Room": "room-dark-room",
    "Print Room": "room-screen-printing-room",
    "Workshop": "room-workshop",
    "Green room": "room-green-room",
}


def set_map_slugs(apps, schema_editor):
    Room = apps.get_model("diary", "Room")
    for name, slug in ROOM_SLUGS.items():
        Room.objects.filter(name=name, map_slug="").update(map_slug=slug)


class Migration(migrations.Migration):

    replaces = [
        ("diary", "0009_add_role_description"),
        ("diary", "0010_widen_rota_notes"),
        ("diary", "0011_add_room_is_primary"),
        ("diary", "0012_add_mediaitem_alt_text"),
        ("diary", "0013_add_eventtemplate_fields"),
        ("diary", "0014_eventtemplate_role_counts"),
        ("diary", "0015_add_event_links"),
        ("diary", "0016_role_badge_flags"),
        ("diary", "0017_role_keyholder_flag"),
        ("diary", "0018_alter_eventtemplaterole_count"),
        ("diary", "0019_site_configuration"),
        ("diary", "0020_event_terms_revision"),
        ("diary", "0021_volunteer_event_mark"),
        ("diary", "0022_rotatentry_role_protect"),
        ("diary", "0023_showing_time_fields"),
        ("diary", "0024_archived_flag"),
        ("diary", "0025_event_template_links"),
        ("diary", "0026_role_wheelchair_accessible_site_config_dormancy"),
        ("diary", "0027_event_approval_metadata"),
        ("diary", "0028_rotaentry_volunteer_fk"),
        ("diary", "0029_siteconfiguration_calendar_slot_min_hour"),
        ("diary", "0030_role_programmer_contact"),
        ("diary", "0031_event_hire_name"),
        ("diary", "0032_roombooking"),
        ("diary", "0033_alter_room_map_slug"),
        ("diary", "0034_room_map_slugs"),
        ("diary", "0035_room_show_column"),
    ]

    dependencies = [
        ("diary", "0008_remove_terms_from_event_model"),
        ("members", "0009_v2"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Guidance for volunteers about this role: what's involved, accessibility notes, links to guides, training requirements, etc.",
            ),
        ),
        migrations.AlterField(
            model_name="showing",
            name="rota_notes",
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name="room",
            name="is_primary",
            field=models.BooleanField(
                default=False,
                help_text="Primary spaces are shown with full colour in the calendar; others are desaturated.",
            ),
        ),
        migrations.AddField(
            model_name="mediaitem",
            name="alt_text",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Describe the image for screen readers and when images fail to load. E.g. "People sitting in an outdoor cinema under a night sky."',
                max_length=255,
                verbose_name="Alt text",
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="copy",
            field=models.TextField(blank=True, max_length=8192, null=True),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="copy_summary",
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="terms",
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="film_information",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="outside_hire",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="rota_notes",
            field=models.TextField(blank=True, default="", max_length=4096),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EventTemplateRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveSmallIntegerField(default=1)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diary.role",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_slots",
                        to="diary.eventtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "EventTemplateRoles",
                "ordering": ["role__name"],
                "unique_together": {("template", "role")},
            },
        ),
        migrations.RunPython(
            code=copy_roles_to_through_model,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="eventtemplate",
            name="roles",
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="roles",
            field=models.ManyToManyField(
                through="diary.EventTemplateRole", to="diary.role"
            ),
        ),
        migrations.CreateModel(
            name="EventLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Short name shown on the link chip, e.g. 'Event folder' or 'Crew chat'.",
                        max_length=80,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=500,
                        validators=[
                            toolkit.diary.validators.validate_event_link_url
                        ],
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order (lower numbers first).",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="diary.event",
                    ),
                ),
            ],
            options={
                "db_table": "EventLinks",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="beginner_friendly",
            field=models.BooleanField(
                default=False,
                help_text="Show the 🌱 beginner-friendly badge on the rota — a great first role for new volunteers.",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="not_wheelchair_accessible",
            field=models.BooleanField(
                default=False,
                help_text="Show the ♿ inaccessible badge on the rota — role may not be suitable for wheelchair users.",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="keyholder_only",
            field=models.BooleanField(
                default=False,
                help_text="Show the 🔑 keyholder badge on the rota — slot must be filled by a trained venue keyholder.",
            ),
        ),
        migrations.AlterField(
            model_name="eventtemplaterole",
            name="count",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Number of slots to create for this role when a new event is made from this template.",
            ),
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "films_start_on_time",
                    models.BooleanField(
                        default=False,
                        help_text="Show a banner on public event detail pages stating that films start on time.",
                    ),
                ),
                (
                    "films_start_on_time_banner_text",
                    models.TextField(
                        blank=True,
                        default="We don't show adverts or trailers, so please arrive promptly, as films start as soon as most people have arrived.",
                        help_text="The banner copy. Only shown when 'Films start on time' is enabled.",
                    ),
                ),
                (
                    "rota_show_tags",
                    models.BooleanField(
                        default=True,
                        help_text="Show event tag badges on the edit rota page.",
                    ),
                ),
                (
                    "rota_clear_email_prompt_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="When clearing a rota slot, prompt the user to email the volunteers list.",
                    ),
                ),
                (
                    "show_archive_images",
                    models.BooleanField(
                        default=True,
                        help_text="If off, hide event images on the public site for events whose showings all predate the 'Images start date' below. Volunteers (authenticated users) always see images. Useful for taking pre-archive imagery offline quickly (e.g. copyright issues).",
                    ),
                ),
                (
                    "images_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Cutoff date for the 'Show archive images' setting above. Has no effect unless that setting is off. Leave blank to disable hiding.",
                        null=True,
                    ),
                ),
                (
                    "max_count_per_role",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="Maximum number of slots per role on a single showing's rota.",
                    ),
                ),
                (
                    "programme_copy_summary_max_chars",
                    models.PositiveSmallIntegerField(
                        default=450,
                        help_text="Maximum length of an event's copy summary (the listing blurb).",
                    ),
                ),
                (
                    "programme_event_terms_min_words",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="Minimum word count in an event's terms before it can be confirmed.",
                    ),
                ),
                (
                    "programme_media_max_size_mb",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Maximum size in megabytes for an uploaded event image.",
                    ),
                ),
                (
                    "mailout_details_days_ahead",
                    models.PositiveSmallIntegerField(
                        default=9,
                        help_text="Days ahead to include detailed event copy in the members mailout.",
                    ),
                ),
                (
                    "mailout_listings_days_ahead",
                    models.PositiveSmallIntegerField(
                        default=14,
                        help_text="Days ahead to include listings in the members mailout.",
                    ),
                ),
                (
                    "membership_length_days",
                    models.PositiveSmallIntegerField(
                        default=365,
                        help_text="Default length of a new membership in days. Only used when membership expiry is enabled.",
                    ),
                ),
                (
                    "default_training_expiry_months",
                    models.PositiveSmallIntegerField(
                        default=12,
                        help_text="Months after which volunteer training records are considered expired.",
                    ),
                ),
                (
                    "image_copyright_guidance_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link shown next to the image upload field — e.g. a Nextcloud doc on image rights.",
                        max_length=500,
                    ),
                ),
                (
                    "alt_text_guidance_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link shown next to the alt-text field — e.g. a guide to writing good alt text.",
                        max_length=500,
                    ),
                ),
            ],
            options={
                "db_table": "SiteConfiguration",
                "verbose_name": "Site configuration",
                "verbose_name_plural": "Site configuration",
            },
        ),
        migrations.RunPython(
            code=seed_singleton,
            reverse_code=noop_reverse,
        ),
        migrations.CreateModel(
            name="EventTermsRevision",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saved_at", models.DateTimeField(auto_now_add=True)),
                ("terms_text", models.TextField(blank=True)),
                ("outside_hire", models.BooleanField()),
                ("private", models.BooleanField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_revisions",
                        to="diary.event",
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-saved_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerEventMark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mark_type",
                    models.CharField(
                        choices=[("star", "Star"), ("shadow", "Shadow")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_marks",
                        to="diary.event",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_marks",
                        to="members.volunteer",
                    ),
                ),
            ],
            options={
                "unique_together": {("volunteer", "event")},
            },
        ),
        migrations.AlterField(
            model_name="rotaentry",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="diary.role"
            ),
        ),
        migrations.AddField(
            model_name="showing",
            name="setup_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="showing",
            name="doors_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="showing",
            name="final_volunteer_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="role",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived roles are hidden from normal use. Roles used in past rota entries cannot be permanently deleted.",
            ),
        ),
        migrations.AddField(
            model_name="eventtag",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Archived tags are hidden from normal use. Tags used on past events cannot be permanently deleted.",
            ),
        ),
        migrations.CreateModel(
            name="EventTemplateLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                (
                    "url",
                    models.URLField(
                        max_length=500,
                        validators=[
                            toolkit.diary.validators.validate_event_link_url
                        ],
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="diary.eventtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "EventTemplateLinks",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.RenameField(
            model_name="role",
            old_name="not_wheelchair_accessible",
            new_name="wheelchair_accessible",
        ),
        migrations.RunSQL(
            sql="UPDATE `Roles` SET wheelchair_accessible = 0",
            reverse_sql="UPDATE `Roles` SET wheelchair_accessible = 0",
        ),
        migrations.AlterField(
            model_name="role",
            name="wheelchair_accessible",
            field=models.BooleanField(
                default=False,
                help_text="Show the ♿ accessible badge on the rota — someone has specifically reviewed this role and confirmed it is suitable for wheelchair users.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="volunteer_dormancy_months",
            field=models.PositiveSmallIntegerField(
                default=24,
                help_text="Mark active volunteers as Dormant if they have not logged in for this many months. Set to 0 to never auto-enforce dormancy. Run the 'auto_dormancy' management command periodically (e.g. via cron) to apply this rule.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="approval_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not recorded"),
                    ("meeting", "Approved at programming meeting"),
                    (
                        "standing",
                        "Standing / regular event — no meeting needed",
                    ),
                ],
                default="",
                help_text="How this event entered the programme.",
                max_length=16,
                verbose_name="Approval status",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="approved_at_meeting_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the programming meeting at which this was approved.",
                null=True,
                verbose_name="Meeting date",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_name",
            field=models.CharField(
                blank=True,
                help_text="Optional identifier, e.g. 'Monday meeting'.",
                max_length=128,
                verbose_name="Meeting name",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="meeting_minutes_url",
            field=models.URLField(
                blank=True,
                help_text="Optional link to the meeting minutes.",
                max_length=500,
                verbose_name="Minutes link",
            ),
        ),
        migrations.AddField(
            model_name="rotaentry",
            name="volunteer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rota_entries",
                to="members.volunteer",
            ),
        ),
        migrations.RunPython(
            code=_add_column,
            reverse_code=_drop_column,
            atomic=False,  # executes raw DDL on MySQL — can't be inside a transaction
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name="siteconfiguration",
                    name="calendar_slot_min_hour",
                    field=models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Earliest hour shown in the 3-day and week calendar views (0–23). Events before this time are still shown but the grid starts here. Default 10 hides the dead early-morning hours.",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="role",
            name="beginner_friendly",
            field=models.BooleanField(
                default=False,
                help_text="Show the 🌱 good-first-role badge on the rota — great for new volunteers.",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="programmer_contact",
            field=models.BooleanField(
                default=False,
                help_text="Mark this as the event's programmer/contact slot — empty slots show a warning on the rota to encourage sign-up.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="hire_name",
            field=models.CharField(
                blank=True,
                help_text="Who is hiring the venue? Shown on the rota so everyone knows who to liaise with.",
                max_length=256,
                verbose_name="Hirer name / organisation",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="map_slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="SVG element ID in the building floorplan (e.g. 'room-cinema'). Leave blank if not on the map.",
            ),
        ),
        migrations.CreateModel(
            name="RoomBooking",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "showing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_bookings",
                        to="diary.showing",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="diary.room",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "RoomBookings",
                "ordering": ["start"],
            },
        ),
        migrations.RunPython(
            code=backfill_room_bookings,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="showing",
            name="room",
        ),
        migrations.AlterField(
            model_name="room",
            name="map_slug",
            field=models.SlugField(
                blank=True,
                default="",
                help_text="SVG element ID in the building floorplan (e.g. 'room-cinema'). Leave blank if not on the map.",
                max_length=64,
            ),
        ),
        migrations.RunPython(
            code=set_map_slugs,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="room",
            name="show_column",
            field=models.BooleanField(
                default=True,
                help_text="Show this room as its own column in the diary list view. Uncheck to bundle bookings into the 'Other rooms' column.",
            ),
        ),
    ]
