# Generated by Django 5.2.11 on 2026-02-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0009_add_role_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="showing",
            name="rota_notes",
            field=models.TextField(blank=True, max_length=4096),
        ),
    ]
