# Generated by Django 5.2.11 on 2026-03-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_widen_rota_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary spaces are shown with full colour in the calendar; others are desaturated.'),
        ),
    ]
