# Generated by Django 5.2.12 on 2026-03-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_role_keyholder_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtemplaterole',
            name='count',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of slots to create for this role when a new event is made from this template.'),
        ),
    ]
