# Generated by Django 5.2.13 on 2026-05-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0028_rotaentry_volunteer_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='calendar_slot_min_hour',
            field=models.PositiveSmallIntegerField(default=10, help_text='Earliest hour shown in the 3-day and week calendar views (0–23). Events before this time are still shown but the grid starts here. Default 10 hides the dead early-morning hours.'),
        ),
        migrations.AlterField(
            model_name='role',
            name='beginner_friendly',
            field=models.BooleanField(default=False, help_text='Show the 🌱 good-first-role badge on the rota — great for new volunteers.'),
        ),
    ]
