# Generated by Django 5.2.13 on 2026-05-12 20:01

from django.db import migrations, models


def _add_column(apps, schema_editor):
    # MySQL/MariaDB DDL is non-transactional: use IF NOT EXISTS so a crash
    # between the ALTER TABLE and the django_migrations INSERT doesn't leave
    # the column missing on the next startup. Other backends (SQLite in tests)
    # use standard schema_editor.add_field, which errors cleanly on duplicate.
    if schema_editor.connection.vendor == "mysql":
        schema_editor.execute(
            "ALTER TABLE SiteConfiguration "
            "ADD COLUMN IF NOT EXISTS calendar_slot_min_hour "
            "smallint(5) unsigned NOT NULL DEFAULT 10"
        )
    else:
        SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
        field = models.PositiveSmallIntegerField(default=10)
        field.set_attributes_from_name("calendar_slot_min_hour")
        with schema_editor.connection.schema_editor() as inner:
            inner.add_field(SiteConfiguration, field)


def _drop_column(apps, schema_editor):
    if schema_editor.connection.vendor == "mysql":
        schema_editor.execute(
            "ALTER TABLE SiteConfiguration DROP COLUMN IF EXISTS calendar_slot_min_hour"
        )
    else:
        SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
        field = models.PositiveSmallIntegerField(default=10)
        field.set_attributes_from_name("calendar_slot_min_hour")
        with schema_editor.connection.schema_editor() as inner:
            inner.remove_field(SiteConfiguration, field)


class Migration(migrations.Migration):

    atomic = False  # MariaDB DDL is non-transactional; IF NOT EXISTS guards against partial runs

    dependencies = [
        ('diary', '0028_rotaentry_volunteer_fk'),
    ]

    operations = [
        migrations.RunPython(_add_column, _drop_column),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='siteconfiguration',
                    name='calendar_slot_min_hour',
                    field=models.PositiveSmallIntegerField(default=10, help_text='Earliest hour shown in the 3-day and week calendar views (0–23). Events before this time are still shown but the grid starts here. Default 10 hides the dead early-morning hours.'),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='beginner_friendly',
            field=models.BooleanField(default=False, help_text='Show the 🌱 good-first-role badge on the rota — great for new volunteers.'),
        ),
    ]
