# Generated by Django 5.2.13 on 2026-05-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0029_siteconfiguration_calendar_slot_min_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='programmer_contact',
            field=models.BooleanField(default=False, help_text="Mark this as the event's programmer/contact slot — empty slots show a warning on the rota to encourage sign-up."),
        ),
    ]
