# Generated by Django 5.2.13 on 2026-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0030_role_programmer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hire_name',
            field=models.CharField(blank=True, help_text='Who is hiring the venue? Shown on the rota so everyone knows who to liaise with.', max_length=256, verbose_name='Hirer name / organisation'),
        ),
    ]
