# Generated by Django 5.2.13 on 2026-05-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0032_roombooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='map_slug',
            field=models.SlugField(blank=True, default='', help_text="SVG element ID in the building floorplan (e.g. 'room-cinema'). Leave blank if not on the map.", max_length=64),
        ),
    ]
