# Generated by Django 5.2.14 on 2026-06-28 13:07

import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# toolkit.diary.migrations.0047_siteconfiguration_rota_clear_prompt_text
# toolkit.diary.migrations.0049_room_more_map_slugs
# toolkit.diary.migrations.0050_remove_siteconfiguration_volunteer_dormancy_months_and_more
# toolkit.diary.migrations.0060_mediaitem_bar_colour_siteconfiguration_thumbnail_crop
# toolkit.diary.migrations.0061_mediaitem_crop_h_mediaitem_crop_w_mediaitem_crop_x_and_more
# toolkit.diary.migrations.0062_siteconfiguration_programme_accent_colour
# toolkit.diary.migrations.0067_merge_notes_into_programming_notes
# toolkit.diary.migrations.0070_siteconfiguration_age_rating_choices_and_more
# toolkit.diary.migrations.0071_siteconfiguration_ticket_link_guidance_html
# toolkit.diary.migrations.0081_update_ticketsource_guidance

ALT_TEXT_GUIDANCE_URL = (
    "https://design102.blog.gov.uk/2022/01/14/"
    "whats-the-alternative-how-to-write-good-alt-text/"
)


def seed_new_fields(apps, schema_editor):
    SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
    vols_email = getattr(settings, "VENUE", {}).get("vols_email", "")
    SiteConfiguration.objects.filter(pk=1, alt_text_guidance_url="").update(
        alt_text_guidance_url=ALT_TEXT_GUIDANCE_URL
    )
    if vols_email:
        SiteConfiguration.objects.filter(pk=1, vols_email="").update(
            vols_email=vols_email
        )


def noop_reverse(apps, schema_editor):
    # Shared no-op reverse for the seed/carry-over data migrations in this
    # squash (0047, 0050). Reversing a seed migration has nothing to undo.
    pass


ROOM_SLUGS_0049 = {
    "Kitchen": "room-kitchen",
    "Snug": "room-snug",
    "Projection Booth": "room-projection-booth",
    "Middle Corridor": "room-middle-corridor",
}


def set_map_slugs_0049(apps, schema_editor):
    Room = apps.get_model("diary", "Room")
    for name, slug in ROOM_SLUGS_0049.items():
        Room.objects.filter(name=name, map_slug="").update(map_slug=slug)


OLD_DORMANCY_MONTHS_DEFAULT = 24


def carry_over_dormancy_value(apps, schema_editor):
    SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
    for config in SiteConfiguration.objects.all():
        months = config.volunteer_dormancy_months
        if months and months != OLD_DORMANCY_MONTHS_DEFAULT:
            config.volunteer_dormancy_days = months * 30
            config.save(update_fields=["volunteer_dormancy_days"])


def _add_columns(apps, schema_editor):
    """Add the three new columns, guarding against pre-existing ones.

    On the dev MariaDB the columns already exist (crop-box feature 9.59 was
    implemented, its migration ran, then the code was reverted but the DB was
    never rolled back). MariaDB supports ADD COLUMN IF NOT EXISTS; SQLite
    (test runner) needs a manual existence check.
    """
    conn = schema_editor.connection
    if conn.vendor == "mysql":
        schema_editor.execute(
            "ALTER TABLE `MediaItems` ADD COLUMN IF NOT EXISTS"
            " `bar_colour` varchar(7) NOT NULL DEFAULT '';"
        )
        schema_editor.execute(
            "ALTER TABLE `SiteConfiguration` ADD COLUMN IF NOT EXISTS"
            " `thumbnail_crop_width` smallint unsigned NOT NULL DEFAULT 600;"
        )
        schema_editor.execute(
            "ALTER TABLE `SiteConfiguration` ADD COLUMN IF NOT EXISTS"
            " `thumbnail_crop_height` smallint unsigned NOT NULL DEFAULT 900;"
        )
    else:
        # SQLite: inspect existing columns before adding.
        with conn.cursor() as cur:
            cur.execute("PRAGMA table_info(MediaItems)")
            media_cols = {r[1] for r in cur.fetchall()}
            cur.execute("PRAGMA table_info(SiteConfiguration)")
            cfg_cols = {r[1] for r in cur.fetchall()}
        if "bar_colour" not in media_cols:
            schema_editor.execute(
                "ALTER TABLE MediaItems ADD COLUMN bar_colour varchar(7) NOT NULL DEFAULT '';"
            )
        if "thumbnail_crop_width" not in cfg_cols:
            schema_editor.execute(
                "ALTER TABLE SiteConfiguration ADD COLUMN thumbnail_crop_width smallint NOT NULL DEFAULT 600;"
            )
        if "thumbnail_crop_height" not in cfg_cols:
            schema_editor.execute(
                "ALTER TABLE SiteConfiguration ADD COLUMN thumbnail_crop_height smallint NOT NULL DEFAULT 900;"
            )


def _remove_columns(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "mysql":
        schema_editor.execute(
            "ALTER TABLE `MediaItems` DROP COLUMN IF EXISTS `bar_colour`;"
        )
        schema_editor.execute(
            "ALTER TABLE `SiteConfiguration` DROP COLUMN IF EXISTS `thumbnail_crop_width`;"
        )
        schema_editor.execute(
            "ALTER TABLE `SiteConfiguration` DROP COLUMN IF EXISTS `thumbnail_crop_height`;"
        )
    # SQLite: DROP COLUMN not supported in older SQLite; skip reverse migration.


def _add_crop_columns(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "mysql":
        for col in ("crop_x", "crop_y", "crop_w", "crop_h"):
            schema_editor.execute(
                f"ALTER TABLE `MediaItems` ADD COLUMN IF NOT EXISTS `{col}` DOUBLE NULL;"
            )
    else:
        with conn.cursor() as cur:
            cur.execute("PRAGMA table_info(MediaItems)")
            media_cols = {r[1] for r in cur.fetchall()}
        for col in ("crop_x", "crop_y", "crop_w", "crop_h"):
            if col not in media_cols:
                schema_editor.execute(
                    f"ALTER TABLE MediaItems ADD COLUMN {col} REAL NULL;"
                )


def _remove_crop_columns(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "mysql":
        for col in ("crop_x", "crop_y", "crop_w", "crop_h"):
            schema_editor.execute(
                f"ALTER TABLE `MediaItems` DROP COLUMN IF EXISTS `{col}`;"
            )


def _add_programme_accent_colour_column(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "mysql":
        schema_editor.execute(
            "ALTER TABLE `SiteConfiguration` ADD COLUMN IF NOT EXISTS"
            " `programme_accent_colour` varchar(7) NOT NULL DEFAULT '#e91e8c';"
        )
    else:
        with conn.cursor() as cur:
            cur.execute("PRAGMA table_info(SiteConfiguration)")
            existing = {r[1] for r in cur.fetchall()}
        if "programme_accent_colour" not in existing:
            schema_editor.execute(
                "ALTER TABLE SiteConfiguration ADD COLUMN"
                " programme_accent_colour varchar(7) NOT NULL DEFAULT '#e91e8c';"
            )


def _remove_programme_accent_colour_column(apps, schema_editor):
    conn = schema_editor.connection
    if conn.vendor == "mysql":
        schema_editor.execute(
            "ALTER TABLE `SiteConfiguration` DROP COLUMN IF EXISTS `programme_accent_colour`;"
        )


def copy_notes_to_programming_notes(apps, schema_editor):
    Event = apps.get_model("diary", "Event")
    for event in Event.objects.exclude(notes__isnull=True).exclude(notes=""):
        if event.programming_notes:
            event.programming_notes = (
                event.notes + "\n\n" + event.programming_notes
            )
        else:
            event.programming_notes = event.notes
        event.save(update_fields=["programming_notes"])


_BBFC_DEFAULTS = [
    {"value": "U", "label": "U — Universal"},
    {"value": "PG", "label": "PG — Parental Guidance"},
    {"value": "12A", "label": "12A — Cinema only, under 12s with adult"},
    {"value": "12", "label": "12"},
    {"value": "15", "label": "15"},
    {"value": "18", "label": "18"},
]


def seed_bbfc_defaults(apps, schema_editor):
    SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
    SiteConfiguration.objects.filter(age_rating_choices=[]).update(
        age_rating_choices=_BBFC_DEFAULTS
    )


_TICKETSOURCE_GUIDANCE_SHORT = (
    "<ol>"
    '<li>Go to <a href="https://www.ticketsource.co.uk" target="_blank" rel="noopener noreferrer">TicketSource</a>'
    " and create a new event with the same title and date.</li>"
    "<li>Set the pricing tier: standard (<strong>£6.50 / £5 concession</strong>) or free."
    " Cheap night: <strong>£3.50 / £3</strong>.</li>"
    "<li>Select the correct seating plan (Cinema layout for film screenings).</li>"
    "<li>Use the exact event title from the toolkit so box office reports match.</li>"
    "<li>Copy the ticket URL and paste it into the <em>Ticket link</em> field above.</li>"
    "</ol>"
)


def seed_ticketsource_guidance(apps, schema_editor):
    SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
    SiteConfiguration.objects.filter(ticket_link_guidance_html="").update(
        ticket_link_guidance_html=_TICKETSOURCE_GUIDANCE_SHORT
    )


_NEXTCLOUD_GUIDE_URL = (
    "/nextcloud/Film%20%26%20Television%20Programming%20Guide.pdf"
)

_TICKETSOURCE_GUIDANCE = (
    '<p>Log in to <a href="https://www.ticketsource.co.uk" target="_blank" rel="noopener noreferrer">TicketSource</a>.'
    " Username: <strong>REDACTED</strong>. Password: ask a member of the film programming group &mdash; it changes regularly.</p>"
    '<p>See also: <a href="{nextcloud_url}" target="_blank" rel="noopener noreferrer">Film &amp; Television Programming Guide (Nextcloud)</a>'
    " for full guidance on TicketSource, pricing, and promotional material.</p>"
    "<ol>"
    "<li>Hover over the <strong>Events</strong> tab and click <strong>New event</strong>. Enter the same title, date, and details as in Toolkit. Click <strong>Save changes</strong>.</li>"
    "<li>Click <strong>Add venue</strong> and type <em>Star and Shadow</em> into the venue name field. Select the first option from the dropdown &mdash; this autocompletes the venue details. Click <strong>Save changes</strong>.</li>"
    "<li>Click <strong>Add date</strong>. Enter the date and start time. You do not need to specify a doors open time or ending time."
    " Set <strong>Stop ticket sales</strong> to <em>1 hour before start time</em>. Click <strong>Save changes</strong>.</li>"
    "<li>Click <strong>Add ticket allocation</strong> and select <em>Tickets are allocated on a seating plan</em>."
    " From the dropdown choose <strong>2025 Seating Plan</strong>."
    " Uncheck the box labelled <em>Enable orphan seat rule on internet bookings</em>. Click <strong>Save changes</strong>.</li>"
    "<li>Click <strong>Pricing category</strong> and add four pricing options:"
    "<ul>"
    "<li><strong>Full price</strong> &mdash; standard: <strong>&pound;6.50</strong>; cheap night: <strong>&pound;3.50</strong></li>"
    "<li><strong>Concessions</strong> &mdash; standard: <strong>&pound;5</strong>; cheap night: <strong>&pound;3</strong></li>"
    "<li><strong>Further concessions</strong> &mdash; for those who need it; set your own price</li>"
    "<li><strong>Gratis / Free</strong> &mdash; for comps. In <em>Advanced settings</em>, check <em>Individual ticket</em>"
    " and set <em>Maximum selection of</em> to <strong>1 ticket</strong>.</li>"
    "</ul>"
    "For free events, set all ticket prices to &pound;0.</li>"
    "<li>Click <strong>Activate event</strong> to make the listing live.</li>"
    "<li>Click <strong>Publicise event</strong> and copy the <strong>Ticket shop URL</strong>."
    " Paste it into the <em>Ticket link</em> field above in Toolkit.</li>"
    "<li>You can also download a QR code from TicketSource to use in print promotion.</li>"
    "</ol>"
).format(nextcloud_url=_NEXTCLOUD_GUIDE_URL)


def update_guidance(apps, schema_editor):
    SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
    SiteConfiguration.objects.update(
        ticket_link_guidance_html=_TICKETSOURCE_GUIDANCE
    )


class Migration(migrations.Migration):

    replaces = [
        ("diary", "0036_siteconfiguration_rota_gap_thresholds"),
        ("diary", "0037_siteconfiguration_access_rider_guidance_url"),
        ("diary", "0038_siteconfiguration_bulletins"),
        ("diary", "0039_siteconfiguration_nav_and_banner"),
        ("diary", "0040_siteconfiguration_bulletin_post_permission"),
        ("diary", "0041_siteconfiguration_donations_intro"),
        ("diary", "0042_event_trailer_url"),
        ("diary", "0043_event_age_restriction"),
        ("diary", "0044_siteconfiguration_max_showing_dates"),
        ("diary", "0045_siteconfiguration_collectives_intro"),
        ("diary", "0046_siteconfiguration_eventlink_extra_allowed_domains"),
        ("diary", "0047_siteconfiguration_rota_clear_prompt_text"),
        ("diary", "0048_siteconfiguration_breakeven_fields"),
        ("diary", "0049_room_more_map_slugs"),
        (
            "diary",
            "0050_remove_siteconfiguration_volunteer_dormancy_months_and_more",
        ),
        ("diary", "0051_volunteer_digest_day"),
        ("diary", "0052_role_qualification_gate"),
        ("diary", "0053_siteconfiguration_general_training_enabled"),
        ("diary", "0054_siteconfiguration_lost_and_found_retain_days"),
        ("diary", "0055_siteconfiguration_community_exchange_enabled"),
        (
            "diary",
            "0056_siteconfiguration_collectives_mailing_list_signup_url",
        ),
        ("diary", "0058_eventtag_filter_group"),
        ("diary", "0059_eventtag_description"),
        (
            "diary",
            "0060_mediaitem_bar_colour_siteconfiguration_thumbnail_crop",
        ),
        (
            "diary",
            "0061_mediaitem_crop_h_mediaitem_crop_w_mediaitem_crop_x_and_more",
        ),
        ("diary", "0062_siteconfiguration_programme_accent_colour"),
        ("diary", "0063_roombooking_date_offset"),
        ("diary", "0064_eventtemplateroom"),
        ("diary", "0065_event_programming_status"),
        ("diary", "0066_siteconfiguration_confirm_label_and_more"),
        ("diary", "0067_merge_notes_into_programming_notes"),
        ("diary", "0068_event_programming_status_changed_at"),
        ("diary", "0069_event_target_month"),
        ("diary", "0070_siteconfiguration_age_rating_choices_and_more"),
        ("diary", "0071_siteconfiguration_ticket_link_guidance_html"),
        ("diary", "0072_alter_siteconfiguration_age_rating_choices"),
        ("diary", "0073_role_stats_label_and_siteconfiguration_stats_fields"),
        ("diary", "0074_siteconfiguration_stats_training_tag_slugs_blank"),
        ("diary", "0075_film_model_and_event_film_fk"),
        ("diary", "0076_siteconfiguration_tmdb_api_key_email"),
        ("diary", "0077_event_cost_fields"),
        ("diary", "0078_siteconfiguration_structured_cost_required"),
        ("diary", "0079_siteconfiguration_last_gasp_email"),
        ("diary", "0080_siteconfiguration_tmdb_api_key"),
        ("diary", "0081_update_ticketsource_guidance"),
        ("diary", "0082_siteconfiguration_suspension_email"),
        ("diary", "0083_omdb_replace_tmdb"),
        ("diary", "0084_cost_rider_and_sound_engineer_fields"),
        ("diary", "0085_role_is_one_shot"),
        ("diary", "0086_siteconfig_permission_fields"),
        ("diary", "0087_diary_read_write_perm_split"),
        ("diary", "0088_siteconfiguration_film_programming_guide_url"),
        ("diary", "0089_add_stats_programming_note"),
        ("diary", "0090_last_gasp_email_enabled"),
    ]

    dependencies = [
        ("diary", "0009_v2"),
        ("members", "0009_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="rota_gap_min_missing",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="Show the 'rota gaps' dashboard widget for showings with at least this many unfilled required slots. Set to 0 to use only the percentage threshold.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="rota_gap_min_pct",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Show the 'rota gaps' dashboard widget for showings where at least this percentage of required slots are unfilled (0–100). Set to 0 to use only the count threshold.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="access_rider_guidance_url",
            field=models.URLField(
                blank=True,
                default="https://weareunlimited.org.uk/resource/creating-your-own-access-rider/",
                help_text="Link shown in the Access Rider section of the volunteer profile — guidance on writing an access rider. Leave blank to hide the link.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bulletin_default_expiry_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="How many days a bulletin stays active if no explicit expiry is set. Default is 30. Set to 0 to keep bulletins active indefinitely by default.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bulletin_guidance",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Guidance shown on the 'Post a bulletin' form. Use this to set local conventions: what kinds of notices belong here, how to write them, and examples of good and bad bulletins.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="show_donations_in_public_nav",
            field=models.BooleanField(
                default=False,
                help_text="Show a 'Donations wishlist' link in the public site navigation, pointing at the labs donations list. Off by default.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="banner_active",
            field=models.BooleanField(
                default=False,
                help_text="Show a site-wide announcement banner at the top of every page (public and toolkit) for important notices.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="banner_level",
            field=models.CharField(
                choices=[
                    ("info", "Info (blue)"),
                    ("warning", "Warning (amber)"),
                    ("critical", "Critical (red)"),
                ],
                default="info",
                help_text="Colour scheme for the banner.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="banner_text",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Banner content. Plain text; line breaks are preserved. Edit this and re-save to issue an updated notice — visitors who previously dismissed the banner will see the new version.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="banner_dismissible",
            field=models.BooleanField(
                default=True,
                help_text="Allow visitors to dismiss the banner. Their choice is stored in their browser only, and resets when the banner text changes.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="bulletin_post_permission",
            field=models.CharField(
                choices=[
                    ("all", "All volunteers"),
                    ("programmer", "Programmers and Panopticon"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can post new bulletins.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="trailer_url",
            field=models.URLField(
                blank=True,
                help_text="Link to a trailer (e.g. YouTube or Vimeo). Shown as a 'Watch trailer' link on the public event page.",
                max_length=500,
                verbose_name="Trailer URL",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="donations_intro",
            field=models.TextField(
                blank=True,
                default="<p>The most valuable things you can give us are your time, energy, and ideas. If you want to get involved, the best place to start is by volunteering at events or joining one of our working groups.</p><p>That said, we do sometimes need physical things too, and this page lists what’s currently useful. Before bringing anything, please check the status: <strong>Wanted</strong> means yes please; <strong>Check first</strong> means it might work but talk to us first; <strong>Not needed</strong> means we’re already well supplied or can’t use it.</p><p>One of our most precious resources as a DIY space is space itself. We share the building across a lot of different groups and uses, and it’s much easier to add things than to remove them. Please don’t drop anything off without checking first, even if it seems obviously useful.</p>",
                help_text="Introductory copy shown at the top of the public donations page. HTML.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="age_restriction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not stated"),
                    ("all_ages", "All ages welcome"),
                    ("16_plus", "16+ only"),
                    ("18_plus", "18+ only"),
                ],
                default="",
                help_text="Under 18s must be accompanied by an adult at all events. Use this field to flag family-friendly events ('All ages welcome') or events with a minimum admission age.",
                max_length=16,
                verbose_name="Age restriction",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="max_showing_dates_shown",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="Maximum number of future showing dates to display on the public event detail page before collapsing extras into a 'Show more' section. Set to 0 to always show all dates.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="collectives_intro",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Introductory copy shown at the top of the public /labs/collectives/ page. Plain text. Leave blank to use the built-in default.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="eventlink_extra_allowed_domains",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Extra domains allowed for event resource links, one per line. Subdomains are accepted (e.g. 'nextcloud.example.org' also allows 'files.nextcloud.example.org'). Built-in domains (riseup.net, nextcloud.com/org, chat.whatsapp.com, linktr.ee) are always allowed.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="rota_clear_email_prompt_text",
            field=models.TextField(
                blank=True,
                default="Slot cleared.\nPlease consider emailing {email} to say that the shift needs covering.",
                help_text="The message shown when a volunteer clears their rota slot. Use {email} as a placeholder; it will be replaced with the volunteers list address set in the 'Volunteers list email' field below. Only shown when 'Rota clear email prompt' is enabled above.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="vols_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="The email address of the volunteers mailing list. Shown in the rota slot-cleared prompt (see above) when the {email} placeholder is used. Seeded from the VENUE settings on first run.",
                max_length=254,
                verbose_name="Volunteers list email",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="alt_text_guidance_url",
            field=models.URLField(
                blank=True,
                default="https://design102.blog.gov.uk/2022/01/14/whats-the-alternative-how-to-write-good-alt-text/",
                help_text="Alt text (alternative text) is a short written description of an image, read aloud by screen readers for blind and partially-sighted users and shown when an image fails to load. This field sets a link shown next to the alt text input when uploading event images — point it at a guide to writing good alt text. Leave blank to hide the link.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="rota_clear_email_prompt_enabled",
            field=models.BooleanField(
                default=True,
                help_text="When a volunteer removes themselves from a rota slot, show a reminder prompt asking them to notify the volunteers list. Edit the prompt text in the field below.",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="rota_show_tags",
            field=models.BooleanField(
                default=True,
                help_text="Show coloured event tag badges (e.g. 'family-friendly', 'accessible') on the edit rota page, along with a filter bar for narrowing the rota by tag. Useful once events are consistently tagged; turn off to reduce visual clutter if tags are rarely used at your venue.",
            ),
        ),
        migrations.RunPython(
            code=seed_new_fields,
            reverse_code=noop_reverse,
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="breakeven_fc_music_threshold",
            field=models.PositiveSmallIntegerField(
                default=750,
                help_text="Gross cost threshold (£) for a music event above which a Finance Collective sign-off is required. Triggers a warning in the break-even calculator.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="breakeven_fc_standard_threshold",
            field=models.PositiveSmallIntegerField(
                default=500,
                help_text="Gross cost threshold (£) for a standard event above which a Finance Collective sign-off is required. Triggers a warning in the break-even calculator.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="breakeven_guidance_note",
            field=models.TextField(
                blank=True,
                default="Opening the doors at S&S costs roughly £200 before any additional costs — make sure this is factored in above. Finance Collective sign-off required if total costs exceed £500 (standard) or £750 (music).",
                help_text="Guidance note shown below the break-even calculator on the event hub page. Plain text.",
            ),
        ),
        migrations.RunPython(
            code=set_map_slugs_0049,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="volunteer_dormancy_days",
            field=models.PositiveSmallIntegerField(
                default=365,
                help_text="Mark active volunteers as Dormant if they have not logged in for this many days. Dormant is a soft, reversible label: it does not disable login or rota signup. Set to 0 to never auto-mark dormancy. Applied by the 'auto_dormancy' management command (run periodically, e.g. via cron) and surfaced on the volunteer pool-health dashboard.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="volunteer_never_logged_in_grace_days",
            field=models.PositiveSmallIntegerField(
                default=90,
                help_text="Mark active volunteers who have never logged in as Dormant once this many days have passed since their account was created (they were inducted but never engaged — likely re-induction candidates). Set to 0 to never auto-mark these. Applied by the 'auto_dormancy' command.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="volunteer_purge_days",
            field=models.PositiveSmallIntegerField(
                default=1095,
                help_text="Flag dormant/retired volunteers as candidates for anonymisation (GDPR data minimisation) once their last activity is older than this many days. Set to 0 to never flag purge candidates. Surfaced on the pool-health dashboard; acted on only via the manual 'purge_stale_volunteers' command — never automatically.",
            ),
        ),
        migrations.RunPython(
            code=carry_over_dormancy_value,
            reverse_code=noop_reverse,
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="volunteer_dormancy_months",
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="volunteer_digest_day",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Disabled"),
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ],
                default=4,
                help_text="Day of the week on which the volunteer digest email is sent. The scheduler fires the digest command daily at 09:00; this setting controls which day it actually sends. Set to Disabled to suppress sending without stopping the scheduler container.",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="required_qualification",
            field=models.ForeignKey(
                blank=True,
                help_text="Qualification volunteers must hold to sign up for this role.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="required_for_roles",
                to="members.qualification",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="bulletin_guidance",
            field=models.TextField(
                blank=True,
                default='Use bulletins for short notices relevant to the whole volunteer community: policy changes, updated contact details, new resources, or anything a volunteer needs to know before their next event.\n\nGood examples: "Keyholders can now be contacted via keyholders@lists.example.com — please use this if your event needs a keyholder." / "The Managing Immediate Risk Policy has been updated and applies to all volunteers: [link]" / "The projection booth door code has changed — use the code previously assigned to the cleaning cupboard."\n\nBefore you post, remember that bulletins go to all 500+ active volunteers. If you need to send a callout ahead of an event, mailing lists are a better route.',
                help_text="Guidance shown on the 'Post a bulletin' form. Use this to set local conventions: what kinds of notices belong here, how to write them, and examples of good and bad bulletins.",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="default_training_expiry_months",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text="Months after which a training record is shown as 'out of date' on the volunteer list. This is informational only — it does not affect rota sign-up. The training gate checks for any record, however old.",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="mailout_details_days_ahead",
            field=models.PositiveSmallIntegerField(
                default=9,
                help_text="This setting controls the members mailout — the periodic programme newsletter sent to people on the membership list (not volunteers, not the public website). Events whose next showing falls within this many days from the mailout send date will have their full event copy (synopsis, terms, etc.) included in the mailout. Events further away than this threshold, but within the listings window below, appear as brief listings only. Default is 9 days.",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="mailout_listings_days_ahead",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="The outer window for the members mailout. Events whose next showing falls within this many days from the mailout send date will appear as brief listings (title, date, and time) even if they are outside the detailed copy window above. Events beyond this window are not included in the mailout at all. Default is 14 days.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="general_training_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Show General Safety Training records and prompts across the volunteer list, profile 'Key dates', and training report. Disable if your venue does not run General Safety Training — role-specific training records remain available regardless of this setting. The GST training type is also hidden from the 'add training record' form when disabled.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="lost_and_found_retain_days",
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text="Number of days to retain unclaimed lost and found items before flagging for disposal. Set to 0 to disable flagging.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="community_exchange_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable the community exchange — a browseable catalogue where volunteers can lend tools or give away items to one another. When off, the section is hidden from the nav.",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="qualification_gate",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("advisory", "Advisory"),
                    ("blocking", "Blocking"),
                ],
                default="off",
                help_text="What happens when a volunteer without the required qualification tries to sign up.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="collectives_mailing_list_signup_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL for the mailing list sign-up page, shown in the help box on the <a href='/toolkit/labs/collectives/'>Collectives page</a>. Leave blank to hide the mailing list hint entirely.",
                max_length=500,
                verbose_name="Mailing list sign-up URL",
            ),
        ),
        migrations.AddField(
            model_name="eventtag",
            name="filter_group",
            field=models.CharField(
                blank=True,
                help_text="If set, this tag contributes to the named filter group on the public programme page.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="eventtag",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="One or two sentences on when to use this tag. Shown as a tooltip on the event edit form.",
                null=True,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=_add_columns,
                    reverse_code=_remove_columns,
                    atomic=False,  # raw DDL on MySQL — can't be inside a transaction
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="mediaitem",
                    name="bar_colour",
                    field=models.CharField(
                        blank=True,
                        default="",
                        help_text="If set, pad the uploaded image to the programme card ratio using bars of this colour, instead of letting the browser crop it. Pick a colour that matches your poster. Only applied when a new image is uploaded.",
                        max_length=7,
                        verbose_name="Letterbox bar colour",
                    ),
                ),
                migrations.AddField(
                    model_name="siteconfiguration",
                    name="thumbnail_crop_width",
                    field=models.PositiveSmallIntegerField(
                        default=600,
                        help_text="Width of the programme card image ratio (e.g. 2 for 2:3, or 600 for 600×900). Used when padding uploaded images with letterbox bars and when generating typographic posters. Default 600 (2:3 portrait).",
                    ),
                ),
                migrations.AddField(
                    model_name="siteconfiguration",
                    name="thumbnail_crop_height",
                    field=models.PositiveSmallIntegerField(
                        default=900,
                        help_text="Height of the programme card image ratio (e.g. 3 for 2:3, or 900 for 600×900). Default 900 (2:3 portrait).",
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=_add_crop_columns,
                    reverse_code=_remove_crop_columns,
                    atomic=False,  # raw DDL on MySQL — can't be inside a transaction
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="mediaitem",
                    name="crop_x",
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="mediaitem",
                    name="crop_y",
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="mediaitem",
                    name="crop_w",
                    field=models.FloatField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name="mediaitem",
                    name="crop_h",
                    field=models.FloatField(blank=True, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="mediaitem",
            name="bar_colour",
            field=models.CharField(
                blank=True,
                default="",
                help_text="If set, the programme grid thumbnail is padded with bars of this colour before being cropped. Your original image is never modified. Leave empty to use the crop box alone.",
                max_length=7,
                verbose_name="Letterbox bar colour",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=_add_programme_accent_colour_column,
                    reverse_code=_remove_programme_accent_colour_column,
                    atomic=False,  # raw DDL on MySQL — can't be inside a transaction
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="siteconfiguration",
                    name="programme_accent_colour",
                    field=models.CharField(
                        default="#e91e8c",
                        help_text="The primary brand colour used in the public programme (hex, e.g. #e91e8c). Shown as a suggested bar colour when editing event images.",
                        max_length=7,
                        verbose_name="Programme accent colour",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="roombooking",
            name="date_offset",
            field=models.IntegerField(
                default=0,
                help_text="Days relative to the showing date: 0 = same day, -1 = day before, +1 = day after.",
            ),
        ),
        migrations.CreateModel(
            name="EventTemplateRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_delta_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Start offset from Showing start (minutes). 0 = same time, -120 = 2 hours before.",
                    ),
                ),
                (
                    "end_delta_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="End offset from Showing start (minutes). Leave blank to use event duration.",
                        null=True,
                    ),
                ),
                (
                    "date_offset",
                    models.IntegerField(
                        default=0,
                        help_text="Days relative to the Showing: 0 = same day, -1 = day before, +1 = day after.",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="template_defaults",
                        to="diary.room",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="default_rooms",
                        to="diary.eventtemplate",
                    ),
                ),
            ],
            options={
                "db_table": "EventTemplateRooms",
                "ordering": ["date_offset", "start_delta_minutes"],
                "unique_together": {("template", "room", "date_offset")},
            },
        ),
        migrations.AddField(
            model_name="event",
            name="programming_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes visible to all logged-in users — use for meeting decisions, conditions, questions for the programmer.",
                verbose_name="Programming notes",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="programming_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("draft", "Draft"),
                    ("proposed", "Proposed for meeting"),
                    ("rejected", "Returned / needs work"),
                ],
                default="active",
                help_text="Internal status for the programming queue. 'Draft' = not yet ready for a meeting; 'Proposed' = queued for discussion; 'Active' = normal/approved event; 'Returned' = sent back for changes.",
                max_length=16,
                verbose_name="Programming status",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="confirm_label",
            field=models.CharField(
                default="Confirm",
                help_text="Label on the button that makes an occurrence public and opens its rota. Cinemas may prefer the short 'Confirm'; venues wanting to spell out the dual effect can use e.g. 'Publish & open rota'.",
                max_length=48,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="occurrence_noun",
            field=models.CharField(
                default="showing",
                help_text="Lowercase singular word for one dated occurrence of an event (e.g. 'showing' for a cinema, 'date' or 'session' elsewhere). Used throughout the event-editing UI.",
                max_length=32,
                verbose_name="Occurrence noun (singular)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="occurrence_noun_plural",
            field=models.CharField(
                default="showings",
                help_text="Plural of the occurrence noun (e.g. 'showings', 'dates').",
                max_length=32,
                verbose_name="Occurrence noun (plural)",
            ),
        ),
        migrations.RunPython(
            code=copy_notes_to_programming_notes,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="event",
            name="notes",
        ),
        migrations.AddField(
            model_name="event",
            name="programming_status_changed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Set automatically whenever programming_status is updated.",
                null=True,
                verbose_name="Status last changed",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="target_month",
            field=models.DateField(
                blank=True,
                help_text="For undated proposals: the rough month being targeted. Always stored as the 1st of the month. Shown in the diary alongside monthly ideas notes.",
                null=True,
                verbose_name="Target month",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="programming_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal working notes — not visible to the public. Use for queue context (e.g. 'looking for a Friday in May — sample date'), meeting decisions, and conditions attached to approval. Financial details and hire contacts belong in Terms.",
                verbose_name="Programmer's notes",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="age_rating_choices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Age-rating options shown in the event edit form. A JSON list of {"value": "...", "label": "..."} objects, e.g. BBFC: U / PG / 12A / 12 / 15 / 18. Leave empty to hide the age restriction field.',
            ),
        ),
        migrations.RunPython(
            code=seed_bbfc_defaults,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="event",
            name="age_restriction",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Age rating or restriction for this event. Options are configured in the site settings.",
                max_length=32,
                verbose_name="Age restriction",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="ticket_link_guidance_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="HTML shown in a collapsible panel directly below the ticket link field on the event edit form. Use this to guide programmers through setting up tickets on your chosen platform. Leave blank to hide the panel entirely.",
                verbose_name="Ticket link setup guidance",
            ),
        ),
        migrations.RunPython(
            code=seed_ticketsource_guidance,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="age_rating_choices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Age-rating options shown in the event edit form. e.g. BBFC: U / PG / 12A / 12 / 15 / 18. Leave the list empty to hide the age restriction field entirely.",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="stats_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional label used to group this role with others in volunteer stats. E.g. set 'Bar' on 'Bar Staff - Shift 1' and 'Bar Staff - Shift 2' so they appear as a single 'Bar' row. Leave blank to use the role name.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="programming_min_event_shifts",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Informal threshold: minimum confirmed non-training shifts before a volunteer is considered eligible to programme their own event. Shown on the volunteer stats page as informational context (never enforced in code).",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="stats_training_tag_slugs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Tag slugs whose events are excluded from the \'event shifts\' count on the volunteer stats page (e.g. inductions and training sessions). JSON list of strings, e.g. ["induction", "training-for-volunteers"].',
            ),
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tmdb_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="The Movie Database numeric ID. Leave blank for works not in TMDB.",
                        null=True,
                        unique=True,
                        verbose_name="TMDB ID",
                    ),
                ),
                (
                    "imdb_id",
                    models.CharField(
                        blank=True,
                        help_text="e.g. tt0036775",
                        max_length=20,
                        verbose_name="IMDB ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("film", "Film"), ("tv", "TV show")],
                        default="film",
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True,
                        help_text="Director(s) or TV creator(s), comma-separated if more than one.",
                        max_length=256,
                    ),
                ),
                (
                    "runtime_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "countries",
                    models.CharField(
                        blank=True, help_text="e.g. GB, US", max_length=256
                    ),
                ),
                (
                    "languages",
                    models.CharField(
                        blank=True,
                        help_text="e.g. English, French",
                        max_length=256,
                    ),
                ),
                (
                    "tmdb_certificate",
                    models.CharField(
                        blank=True,
                        help_text="UK certificate as returned by TMDB. For reference — the canonical public-facing cert is set separately on the event.",
                        max_length=16,
                        verbose_name="Certificate (TMDB)",
                    ),
                ),
                (
                    "overview",
                    models.TextField(
                        blank=True,
                        help_text="Plot summary from TMDB. Internal reference only — not shown publicly.",
                    ),
                ),
                (
                    "tmdb_poster_path",
                    models.CharField(blank=True, max_length=256),
                ),
                (
                    "tmdb_fetched_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal programmer notes about this title.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title", "year"],
            },
        ),
        migrations.AddField(
            model_name="event",
            name="film",
            field=models.ForeignKey(
                blank=True,
                help_text="Structured film/TV metadata. Optional — link via the film search in the edit form.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screenings",
                to="diary.film",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="tmdb_api_key_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Email address of the account registered with The Movie Database (TMDB) that owns the API key. For reference only — the API key itself is set via the TMDB_API_KEY environment variable. Leave blank if TMDB integration is not in use.",
                max_length=254,
                verbose_name="TMDB API key contact email",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cost_distributor",
            field=models.CharField(
                blank=True,
                help_text="The distribution company or booker contact (film licence / performer fee).",
                max_length=256,
                null=True,
                verbose_name="Distributor / booker",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cost_fee_includes_vat",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Fee includes VAT"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cost_flat_fee_gbp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed licence or performance fee in pounds.",
                max_digits=8,
                null=True,
                verbose_name="Flat fee (£)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cost_minimum_guarantee_gbp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Guaranteed minimum payment regardless of door takings.",
                max_digits=8,
                null=True,
                verbose_name="Minimum guarantee (£)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cost_percentage_split",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Percentage of net door takings paid to the distributor/performer.",
                max_digits=5,
                null=True,
                verbose_name="% split to distributor",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cost_total_gbp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total agreed fee (performer / hire).",
                max_digits=8,
                null=True,
                verbose_name="Total cost (£)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cost_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("film_license", "Film licence"),
                    ("performer_fee", "Performer fee / gig"),
                    ("venue_hire", "Venue hire"),
                    ("internal", "Internal / volunteer"),
                    ("tbc", "TBC"),
                ],
                help_text="The nature of the financial deal for this event.",
                max_length=32,
                null=True,
                verbose_name="Cost type",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="technical_notes",
            field=models.TextField(
                blank=True,
                help_text="AV / tech rider requirements, projection format, sound spec, etc. Kept separate from financial terms so the two don't get conflated.",
                max_length=4096,
                null=True,
                verbose_name="Technical notes",
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="cost_distributor",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Distributor / booker",
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="cost_fee_includes_vat",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Fee includes VAT"
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="cost_flat_fee_gbp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Flat fee (£)",
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="cost_minimum_guarantee_gbp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Minimum guarantee (£)",
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="cost_percentage_split",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="% split to distributor",
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="cost_total_gbp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Total cost (£)",
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="cost_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("film_license", "Film licence"),
                    ("performer_fee", "Performer fee / gig"),
                    ("venue_hire", "Venue hire"),
                    ("internal", "Internal / volunteer"),
                    ("tbc", "TBC"),
                ],
                max_length=32,
                null=True,
                verbose_name="Cost type",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="structured_cost_terms_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable structured cost fields (cost type, flat fee, % split, etc.) on event edit forms. When on, programmers can record the deal type directly rather than free-texting it into Terms. The Terms textarea remains available for unusual arrangements and legacy records.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="structured_cost_required",
            field=models.BooleanField(
                default=False,
                help_text="Require cost type to be set (to something other than TBC) before any showing can be confirmed. Only takes effect when structured cost terms are enabled above. When cost type is set, the terms word-count check is automatically waived; TBC still falls back to the terms word-count check.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="last_gasp_cooldown_days",
            field=models.PositiveSmallIntegerField(
                default=30,
                help_text="How many days must pass before a second last-gasp email can be sent to the same volunteer.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="last_gasp_email_body",
            field=models.TextField(
                blank=True,
                help_text="Body of the last-gasp email. Use {name} for the volunteer's name and {venue} for the venue name. Leave blank to disable sending.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="last_gasp_email_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject line for the last-gasp re-engagement email. Use {name} for the volunteer's name and {venue} for the venue name.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="tmdb_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="API key for The Movie Database (TMDB). Used for film search and metadata import. Generate or view your key at https://www.themoviedb.org/settings/api. If set here, this takes precedence over the TMDB_API_KEY environment variable.",
                max_length=256,
                verbose_name="TMDB API key",
            ),
        ),
        migrations.RunPython(
            code=update_guidance,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="suspension_email_subject",
            field=models.CharField(
                blank=True,
                default="Your volunteer account at {venue}",
                help_text="Subject line for the email offered when suspending a volunteer. Supports {name} and {venue} variables.",
                max_length=300,
                verbose_name="Suspension email subject",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="suspension_email_body",
            field=models.TextField(
                blank=True,
                default="Hi {name},\n\nThis is to let you know that your volunteer account at {venue} has been suspended. Your login is currently disabled and you have been removed from upcoming shifts.\n\nIf you have any questions or would like to discuss this, please get in touch.\n\nBest wishes,\n{venue}",
                help_text="Body of the email offered when suspending a volunteer. Supports {name} and {venue} variables.",
                verbose_name="Suspension email body",
            ),
        ),
        migrations.RemoveField(
            model_name="film",
            name="tmdb_certificate",
        ),
        migrations.RemoveField(
            model_name="film",
            name="tmdb_fetched_at",
        ),
        migrations.RemoveField(
            model_name="film",
            name="tmdb_id",
        ),
        migrations.RemoveField(
            model_name="film",
            name="tmdb_poster_path",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="tmdb_api_key",
        ),
        migrations.RemoveField(
            model_name="siteconfiguration",
            name="tmdb_api_key_email",
        ),
        migrations.AddField(
            model_name="film",
            name="poster_url",
            field=models.CharField(
                blank=True,
                help_text="Direct URL to a poster image. Set automatically from OMDb.",
                max_length=512,
                verbose_name="Poster URL",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="certificate_lookup_url",
            field=models.CharField(
                blank=True,
                default="https://www.bbfc.co.uk/search?q={title}",
                help_text="URL template for looking up a film's certificate. Use {title} and {year} as placeholders — they will be URL-encoded and substituted when the link is generated. Example (BBFC): https://www.bbfc.co.uk/search?q={title} Leave blank to hide the lookup link.",
                max_length=512,
                verbose_name="Certificate lookup URL",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="omdb_api_key",
            field=models.CharField(
                blank=True,
                default="",
                help_text="API key for the Open Movie Database (OMDb). Used for film search and metadata import. Get a free key at https://www.omdbapi.com/apikey.aspx. If set here, this takes precedence over the OMDB_API_KEY environment variable.",
                max_length=256,
                verbose_name="OMDb API key",
            ),
        ),
        migrations.AlterField(
            model_name="film",
            name="overview",
            field=models.TextField(
                blank=True,
                help_text="Plot summary. Internal reference only — not shown publicly.",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cost_rider_notes",
            field=models.TextField(
                blank=True,
                help_text="Food, drink, accommodation, or other rider requirements for the performer or hirer.",
                max_length=4096,
                null=True,
                verbose_name="Hospitality / rider",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cost_sound_engineer_fee_gbp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Sound engineer fee (£)",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cost_sound_engineer_name",
            field=models.CharField(
                blank=True,
                help_text="Name or contact for the sound engineer, if applicable.",
                max_length=256,
                null=True,
                verbose_name="Sound engineer",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="cost_sound_engineer_paid_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("venue", "Venue"),
                    ("performer", "Performer"),
                    ("hirer", "Hirer"),
                ],
                max_length=16,
                null=True,
                verbose_name="Sound engineer paid by",
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="cost_rider_notes",
            field=models.TextField(
                blank=True,
                max_length=4096,
                null=True,
                verbose_name="Hospitality / rider",
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="cost_sound_engineer_fee_gbp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Sound engineer fee (£)",
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="cost_sound_engineer_name",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Sound engineer",
            ),
        ),
        migrations.AddField(
            model_name="eventtemplate",
            name="cost_sound_engineer_paid_by",
            field=models.CharField(
                blank=True,
                choices=[
                    ("venue", "Venue"),
                    ("performer", "Performer"),
                    ("hirer", "Hirer"),
                ],
                max_length=16,
                null=True,
                verbose_name="Sound engineer paid by",
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="is_one_shot",
            field=models.BooleanField(
                default=False,
                help_text="One-shot roles are created on the fly for a specific showing and do not appear in the permanent roles list.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_diary_calendar",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can access the calendar edit view.",
                max_length=12,
                verbose_name="Diary — calendar",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_diary_reports",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can access copy, terms, and text reports.",
                max_length=12,
                verbose_name="Diary — reports",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_donations_manage",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can access the donations management page.",
                max_length=12,
                verbose_name="Website — donations manage",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_event_tags",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can edit event tags.",
                max_length=12,
                verbose_name="Diary — event tags",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_event_templates",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can access event templates (list and detail). Template import always requires Panopticon.",
                max_length=12,
                verbose_name="Diary — event templates",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_printed_programmes",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can upload printed programmes.",
                max_length=12,
                verbose_name="Diary — printed programmes",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_roles",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can edit rota roles.",
                max_length=12,
                verbose_name="Diary — roles",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_rooms",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can edit rooms.",
                max_length=12,
                verbose_name="Diary — rooms",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_rota_vacancies",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="volunteer",
                help_text="Who can see the rota vacancies page.",
                max_length=12,
                verbose_name="Rota — vacancies page",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_diary_read",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can access the diary editing list.",
                max_length=12,
                verbose_name="Diary — edit list",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="perm_diary_read",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="volunteer",
                help_text="Who can view the diary editing list (read-only for volunteers; event editing always requires Programmer+).",
                max_length=12,
                verbose_name="Diary — view diary list",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_programming_queue_read",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can access the programming queue.",
                max_length=12,
                verbose_name="Diary — programming queue",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="perm_programming_queue_read",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="volunteer",
                help_text="Who can view the programming queue.",
                max_length=12,
                verbose_name="Diary — programming queue (view)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="perm_programming_queue_write",
            field=models.CharField(
                choices=[
                    ("volunteer", "All volunteers"),
                    ("programmer", "Programmer+"),
                    ("panopticon", "Panopticon only"),
                ],
                default="programmer",
                help_text="Who can approve, return, or skip events in the programming queue.",
                max_length=12,
                verbose_name="Diary — programming queue (change status)",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="film_programming_guide_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL linked at the bottom of the ticket link setup guide panel on the event edit form. Typically a full guide to your ticketing platform. Leave blank to omit the link.",
                verbose_name="Film programming guide URL",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="stats_programming_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Optional extra text shown below the programming eligibility count on the volunteer stats page. Plain text only. Leave blank to show nothing.",
                verbose_name="Programming eligibility note",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="programming_min_event_shifts",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Minimum confirmed non-training shifts before a volunteer is considered ready to programme their own event. Shown on the volunteer stats page as a target — never enforced by the system.",
                verbose_name="Programming eligibility threshold",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="stats_training_tag_slugs",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Events tagged with any of these are excluded from a volunteer's confirmed shift count on the stats page. Use this to separate training and induction sessions from regular programming activity.",
                verbose_name="Tags excluded from shift count",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="last_gasp_email_enabled",
            field=models.BooleanField(
                default=False,
                help_text="A last-gasp email is a final, optional re-engagement message sent to a volunteer before their account is anonymised or deleted under data-retention rules — a courtesy “we’re about to remove your data, here’s a chance to come back” note. When enabled, the pool health page shows a button to send one to each purge candidate. (The email-address export, for sending outside the toolkit, is always available regardless of this setting.)",
                verbose_name="Enable last-gasp email features",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="last_gasp_email_body",
            field=models.TextField(
                blank=True,
                help_text="Body text. Use {name} for the volunteer's name and {venue} for the venue name. Can be left blank even when the feature is enabled — the compose page will still open so you can write a message from scratch each time.",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="last_gasp_email_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject line. Use {name} for the volunteer's name and {venue} for the venue name.",
                max_length=200,
            ),
        ),
    ]
