# Generated by Django 5.2.14 on 2026-07-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0038_printed_programme_archive_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='consent_renewal_days',
            field=models.PositiveIntegerField(default=365, help_text="Days after a volunteer's last consent before they're asked to reconfirm it. Set to 0 to disable renewal reminders. Applied by the 'send_consent_renewal_reminders' management command (run periodically, e.g. via cron)."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='consent_renewal_grace_days',
            field=models.PositiveIntegerField(default=30, help_text='Days after a renewal reminder is sent before the volunteer is flagged as consent-overdue for manual review (shown on the volunteer list).'),
        ),
    ]
