# Generated by Django 5.2.14 on 2026-07-02 13:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0039_siteconfiguration_consent_renewal_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='budget_lines_enabled',
            field=models.BooleanField(default=False, help_text="EXPERIMENTAL -- not yet well-tested in real use, and may not survive contact with the Collective's actual workflow; the live spreadsheet remains the working solution unless this is proven better. Enable the itemised budget section (estimate vs actual, by category) on event edit forms. Would replace the 'Budget template.xlsx' spreadsheet workflow. Independent of the structured cost terms flag above -- deal terms describe one negotiated fee; budget lines describe everything else. Off by default while trialled with the Programming/Finance Collective.", verbose_name="Budget lines enabled (experimental)"),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='late_licence_fee_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Default estimate for the 'Fees > Late night licence' budget line on music gigs. Editable per-event since the rate occasionally changes.", max_digits=8, null=True, verbose_name='Late licence fee (£)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='vat_rate_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text="Standard VAT rate used for the net/gross display calculation when a cost's 'Fee includes VAT' flag is set. Display only -- no VAT return generation.", max_digits=5, verbose_name='VAT rate (%)'),
        ),
        migrations.CreateModel(
            name='EventBudgetLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming')], max_length=8)),
                ('category', models.CharField(max_length=64)),
                ('item', models.CharField(blank=True, max_length=128)),
                ('estimate_gbp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimate_source', models.CharField(choices=[('manual', 'Manual entry'), ('deal_terms', 'Linked to deal terms'), ('site_default', 'Site default'), ('calculator', 'Break-even calculator')], default='manual', max_length=16)),
                ('actual_gbp', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, max_length=1024)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_lines', to='diary.event')),
            ],
            options={
                'ordering': ['direction', 'order', 'pk'],
            },
        ),
    ]
