# Generated by Django 5.2.14 on 2026-07-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0040_siteconfiguration_budget_lines_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='rota_show_tags',
            field=models.BooleanField(default=False, help_text="Show coloured event tag badges (e.g. 'family-friendly', 'accessible') on the edit rota page, along with a filter bar for narrowing the rota by tag. Useful once events are consistently tagged; turn off to reduce visual clutter if tags are rarely used at your venue."),
        ),
    ]
