# Generated by Django 5.2.14 on 2026-05-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0041_siteconfiguration_donations_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trailer_url',
            field=models.URLField(blank=True, help_text="Link to a trailer (e.g. YouTube or Vimeo). Shown as a 'Watch trailer' link on the public event page.", max_length=500, verbose_name='Trailer URL'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='donations_intro',
            field=models.TextField(blank=True, default='<p>The most valuable things you can give us are your time, energy, and ideas. If you want to get involved, the best place to start is by volunteering at events or joining one of our working groups.</p><p>That said, we do sometimes need physical things too, and this page lists what’s currently useful. Before bringing anything, please check the status: <strong>Wanted</strong> means yes please; <strong>Check first</strong> means it might work but talk to us first; <strong>Not needed</strong> means we’re already well supplied or can’t use it.</p><p>One of our most precious resources as a DIY space is space itself. We share the building across a lot of different groups and uses, and it’s much easier to add things than to remove them. Please don’t drop anything off without checking first, even if it seems obviously useful.</p>', help_text='Introductory copy shown at the top of the public donations page. HTML.'),
        ),
    ]
