# Generated by Django 5.2.14 on 2026-05-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0042_event_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(blank=True, choices=[('', 'Not stated'), ('all_ages', 'All ages welcome'), ('16_plus', '16+ only'), ('18_plus', '18+ only')], default='', help_text="Under 18s must be accompanied by an adult at all events. Use this field to flag family-friendly events ('All ages welcome') or events with a minimum admission age.", max_length=16, verbose_name='Age restriction'),
        ),
    ]
