# Generated by Django 5.2.14 on 2026-05-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0043_event_age_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='max_showing_dates_shown',
            field=models.PositiveSmallIntegerField(default=5, help_text="Maximum number of future showing dates to display on the public event detail page before collapsing extras into a 'Show more' section. Set to 0 to always show all dates."),
        ),
    ]
