# Generated by Django 5.2.14 on 2026-05-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0044_siteconfiguration_max_showing_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='collectives_intro',
            field=models.TextField(blank=True, default='', help_text='Introductory copy shown at the top of the public /labs/collectives/ page. Plain text. Leave blank to use the built-in default.'),
        ),
    ]
