# Generated by Django 5.2.14 on 2026-05-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0045_siteconfiguration_collectives_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='eventlink_extra_allowed_domains',
            field=models.TextField(blank=True, default='', help_text="Extra domains allowed for event resource links, one per line. Subdomains are accepted (e.g. 'nextcloud.example.org' also allows 'files.nextcloud.example.org'). Built-in domains (riseup.net, nextcloud.com/org, chat.whatsapp.com, linktr.ee) are always allowed."),
        ),
    ]
