# Generated by Django 5.2.14 on 2026-05-28 19:57

from django.conf import settings
from django.db import migrations, models


ALT_TEXT_GUIDANCE_URL = (
    "https://design102.blog.gov.uk/2022/01/14/"
    "whats-the-alternative-how-to-write-good-alt-text/"
)


def seed_new_fields(apps, schema_editor):
    SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
    vols_email = getattr(settings, "VENUE", {}).get("vols_email", "")
    SiteConfiguration.objects.filter(pk=1, alt_text_guidance_url="").update(
        alt_text_guidance_url=ALT_TEXT_GUIDANCE_URL
    )
    if vols_email:
        SiteConfiguration.objects.filter(pk=1, vols_email="").update(
            vols_email=vols_email
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0046_siteconfiguration_eventlink_extra_allowed_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='rota_clear_email_prompt_text',
            field=models.TextField(blank=True, default='Slot cleared.\nPlease consider emailing {email} to say that the shift needs covering.', help_text="The message shown when a volunteer clears their rota slot. Use {email} as a placeholder; it will be replaced with the volunteers list address set in the 'Volunteers list email' field below. Only shown when 'Rota clear email prompt' is enabled above."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='vols_email',
            field=models.EmailField(blank=True, default='', help_text='The email address of the volunteers mailing list. Shown in the rota slot-cleared prompt (see above) when the {email} placeholder is used. Seeded from the VENUE settings on first run.', max_length=254, verbose_name='Volunteers list email'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='alt_text_guidance_url',
            field=models.URLField(blank=True, default='https://design102.blog.gov.uk/2022/01/14/whats-the-alternative-how-to-write-good-alt-text/', help_text='Alt text (alternative text) is a short written description of an image, read aloud by screen readers for blind and partially-sighted users and shown when an image fails to load. This field sets a link shown next to the alt text input when uploading event images — point it at a guide to writing good alt text. Leave blank to hide the link.', max_length=500),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='rota_clear_email_prompt_enabled',
            field=models.BooleanField(default=True, help_text='When a volunteer removes themselves from a rota slot, show a reminder prompt asking them to notify the volunteers list. Edit the prompt text in the field below.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='rota_show_tags',
            field=models.BooleanField(default=True, help_text="Show coloured event tag badges (e.g. 'family-friendly', 'accessible') on the edit rota page, along with a filter bar for narrowing the rota by tag. Useful once events are consistently tagged; turn off to reduce visual clutter if tags are rarely used at your venue."),
        ),
        migrations.RunPython(seed_new_fields, noop_reverse),
    ]
