# Generated by Django 5.2.14 on 2026-05-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0047_siteconfiguration_rota_clear_prompt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='breakeven_fc_music_threshold',
            field=models.PositiveSmallIntegerField(default=750, help_text='Gross cost threshold (£) for a music event above which a Finance Collective sign-off is required. Triggers a warning in the break-even calculator.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='breakeven_fc_standard_threshold',
            field=models.PositiveSmallIntegerField(default=500, help_text='Gross cost threshold (£) for a standard event above which a Finance Collective sign-off is required. Triggers a warning in the break-even calculator.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='breakeven_guidance_note',
            field=models.TextField(blank=True, default='Opening the doors at S&S costs roughly £200 before any additional costs — make sure this is factored in above. Finance Collective sign-off required if total costs exceed £500 (standard) or £750 (music).', help_text='Guidance note shown below the break-even calculator on the event hub page. Plain text.'),
        ),
    ]
