# Generated by Django 5.2.14 on 2026-05-29 16:59

from django.db import migrations, models

# The old setting's default. If a site left dormancy at this value we treat it as
# "untouched" and adopt the new days-based default (365) rather than mechanically
# converting 24 months -> 720 days. A non-default months value is a deliberate
# choice and is carried over as months * 30.
OLD_DORMANCY_MONTHS_DEFAULT = 24


def carry_over_dormancy_value(apps, schema_editor):
    SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
    for config in SiteConfiguration.objects.all():
        months = config.volunteer_dormancy_months
        if months and months != OLD_DORMANCY_MONTHS_DEFAULT:
            config.volunteer_dormancy_days = months * 30
            config.save(update_fields=["volunteer_dormancy_days"])


def noop_reverse(apps, schema_editor):
    # Reversing re-adds volunteer_dormancy_months with its default; nothing to copy back.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0049_room_more_map_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='volunteer_dormancy_days',
            field=models.PositiveSmallIntegerField(default=365, help_text="Mark active volunteers as Dormant if they have not logged in for this many days. Dormant is a soft, reversible label: it does not disable login or rota signup. Set to 0 to never auto-mark dormancy. Applied by the 'auto_dormancy' management command (run periodically, e.g. via cron) and surfaced on the volunteer pool-health dashboard."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='volunteer_never_logged_in_grace_days',
            field=models.PositiveSmallIntegerField(default=90, help_text="Mark active volunteers who have never logged in as Dormant once this many days have passed since their account was created (they were inducted but never engaged — likely re-induction candidates). Set to 0 to never auto-mark these. Applied by the 'auto_dormancy' command."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='volunteer_purge_days',
            field=models.PositiveSmallIntegerField(default=1095, help_text="Flag dormant/retired volunteers as candidates for anonymisation (GDPR data minimisation) once their last activity is older than this many days. Set to 0 to never flag purge candidates. Surfaced on the pool-health dashboard; acted on only via the manual 'purge_stale_volunteers' command — never automatically."),
        ),
        migrations.RunPython(carry_over_dormancy_value, noop_reverse),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='volunteer_dormancy_months',
        ),
    ]
