# Generated by Django 5.2.14 on 2026-05-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0050_remove_siteconfiguration_volunteer_dormancy_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='volunteer_digest_day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Disabled'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=4, help_text='Day of the week on which the volunteer digest email is sent. The scheduler fires the digest command daily at 09:00; this setting controls which day it actually sends. Set to Disabled to suppress sending without stopping the scheduler container.'),
        ),
    ]
