# Generated by Django 5.2.14 on 2026-05-31 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0051_volunteer_digest_day'),
        ('members', '0022_qualification_volunteerqualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='qualification_gate',
            field=models.CharField(choices=[('off', 'Off'), ('advisory', 'Advisory — warn but allow'), ('blocking', 'Blocking — must hold qualification')], default='off', help_text='What happens when a volunteer without the required qualification tries to sign up.', max_length=10),
        ),
        migrations.AddField(
            model_name='role',
            name='required_qualification',
            field=models.ForeignKey(blank=True, help_text='Qualification volunteers must hold to sign up for this role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_for_roles', to='members.qualification'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='bulletin_guidance',
            field=models.TextField(blank=True, default='Use bulletins for short notices relevant to the whole volunteer community: policy changes, updated contact details, new resources, or anything a volunteer needs to know before their next event.\n\nGood examples: "Keyholders can now be contacted via keyholders@lists.example.com — please use this if your event needs a keyholder." / "The Managing Immediate Risk Policy has been updated and applies to all volunteers: [link]" / "The projection booth door code has changed — use the code previously assigned to the cleaning cupboard."\n\nBefore you post, remember that bulletins go to all 500+ active volunteers. If you need to send a callout ahead of an event, mailing lists are a better route.', help_text="Guidance shown on the 'Post a bulletin' form. Use this to set local conventions: what kinds of notices belong here, how to write them, and examples of good and bad bulletins."),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='default_training_expiry_months',
            field=models.PositiveSmallIntegerField(default=12, help_text="Months after which a training record is shown as 'out of date' on the volunteer list. This is informational only — it does not affect rota sign-up. The training gate checks for any record, however old."),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='mailout_details_days_ahead',
            field=models.PositiveSmallIntegerField(default=9, help_text='This setting controls the members mailout — the periodic programme newsletter sent to people on the membership list (not volunteers, not the public website). Events whose next showing falls within this many days from the mailout send date will have their full event copy (synopsis, terms, etc.) included in the mailout. Events further away than this threshold, but within the listings window below, appear as brief listings only. Default is 9 days.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='mailout_listings_days_ahead',
            field=models.PositiveSmallIntegerField(default=14, help_text='The outer window for the members mailout. Events whose next showing falls within this many days from the mailout send date will appear as brief listings (title, date, and time) even if they are outside the detailed copy window above. Events beyond this window are not included in the mailout at all. Default is 14 days.'),
        ),
    ]
