# Generated by Django 5.2.14 on 2026-06-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0054_siteconfiguration_lost_and_found_retain_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='community_exchange_enabled',
            field=models.BooleanField(default=False, help_text='Enable the community exchange — a browseable catalogue where volunteers can lend tools or give away items to one another. When off, the section is hidden from the nav.'),
        ),
        migrations.AlterField(
            model_name='role',
            name='qualification_gate',
            field=models.CharField(choices=[('off', 'Off'), ('advisory', 'Advisory'), ('blocking', 'Blocking')], default='off', help_text='What happens when a volunteer without the required qualification tries to sign up.', max_length=10),
        ),
    ]
