# Generated by Django 5.2.14 on 2026-06-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0055_siteconfiguration_community_exchange_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='collectives_mailing_list_signup_url',
            field=models.URLField(blank=True, default='', help_text="URL for the mailing list sign-up page, shown in the help box on the <a href='/toolkit/labs/collectives/'>Collectives page</a>. Leave blank to hide the mailing list hint entirely.", max_length=500, verbose_name='Mailing list sign-up URL'),
        ),
    ]
