# Generated by Django 5.2.14 on 2026-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0057_mediaitem_crop_box_and_thumbnail_dims'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtag',
            name='filter_group',
            field=models.CharField(blank=True, help_text='If set, this tag contributes to the named filter group on the public programme page.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='thumbnail_crop_height',
            field=models.PositiveSmallIntegerField(default=900, help_text='Height in pixels of the cropped index thumbnail. See width above. Common ratios: 600×900 (2:3 portrait — film one-sheet standard), 600×600 (1:1 square), 600×450 (4:3 — suits UK quad and lobby card art), 600×400 (3:2 landscape).'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='thumbnail_crop_width',
            field=models.PositiveSmallIntegerField(default=600, help_text='Width in pixels of the cropped index thumbnail. Pairs with the height below to set the crop aspect ratio shown in the image crop tool on each event edit page. <strong>2:3 portrait (600×900) is the right default</strong> — it matches the US theatrical one-sheet, the format used by TMDb, IMDb, Letterboxd, and the major archive sites (Criterion, MUBI, TCM) for both modern releases and digitised classics going back to the silent era. If you frequently show UK films and use the British quad (which is landscape 4:3), consider 600×450. For a clean square grid, use 600×600. Changes here affect the crop box aspect ratio immediately but do <em>not</em> regenerate existing thumbnails — re-save each event image to apply.'),
        ),
    ]
