# Generated by Django 5.2.14 on 2026-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0056_siteconfiguration_collectives_mailing_list_signup_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtag',
            name='filter_group',
            field=models.CharField(blank=True, help_text='If set, this tag contributes to the named filter group on the public programme page.', max_length=50, null=True),
        ),
    ]
