# Generated by Django 5.2.14 on 2026-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0058_eventtag_filter_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtag',
            name='description',
            field=models.TextField(blank=True, help_text='One or two sentences on when to use this tag. Shown as a tooltip on the event edit form.', null=True),
        ),
    ]
