# Generated by Django 5.2.14 on 2026-06-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0062_siteconfiguration_programme_accent_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='date_offset',
            field=models.IntegerField(default=0, help_text='Days relative to the showing date: 0 = same day, -1 = day before, +1 = day after.'),
        ),
    ]
