# Generated by Django 5.2.14 on 2026-06-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0063_roombooking_date_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTemplateRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_delta_minutes', models.IntegerField(default=0, help_text='Start offset from Showing start (minutes). 0 = same time, -120 = 2 hours before.')),
                ('end_delta_minutes', models.IntegerField(blank=True, help_text='End offset from Showing start (minutes). Leave blank to use event duration.', null=True)),
                ('date_offset', models.IntegerField(default=0, help_text='Days relative to the Showing: 0 = same day, -1 = day before, +1 = day after.')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_defaults', to='diary.room')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_rooms', to='diary.eventtemplate')),
            ],
            options={
                'db_table': 'EventTemplateRooms',
                'ordering': ['date_offset', 'start_delta_minutes'],
                'unique_together': {('template', 'room', 'date_offset')},
            },
        ),
    ]
