# Generated by Django 5.2.14 on 2026-06-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0064_eventtemplateroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='programming_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible to all logged-in users — use for meeting decisions, conditions, questions for the programmer.', verbose_name='Programming notes'),
        ),
        migrations.AddField(
            model_name='event',
            name='programming_status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('draft', 'Draft'), ('proposed', 'Proposed for meeting'), ('rejected', 'Returned / needs work')], default='active', help_text="Internal status for the programming queue. 'Draft' = not yet ready for a meeting; 'Proposed' = queued for discussion; 'Active' = normal/approved event; 'Returned' = sent back for changes.", max_length=16, verbose_name='Programming status'),
        ),
    ]
