# Generated by Django 5.2.14 on 2026-06-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0065_event_programming_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='confirm_label',
            field=models.CharField(default='Confirm', help_text="Label on the button that makes an occurrence public and opens its rota. Cinemas may prefer the short 'Confirm'; venues wanting to spell out the dual effect can use e.g. 'Publish & open rota'.", max_length=48),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='occurrence_noun',
            field=models.CharField(default='showing', help_text="Lowercase singular word for one dated occurrence of an event (e.g. 'showing' for a cinema, 'date' or 'session' elsewhere). Used throughout the event-editing UI.", max_length=32, verbose_name='Occurrence noun (singular)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='occurrence_noun_plural',
            field=models.CharField(default='showings', help_text="Plural of the occurrence noun (e.g. 'showings', 'dates').", max_length=32, verbose_name='Occurrence noun (plural)'),
        ),
    ]
