# Generated by Django 5.2.14 on 2026-06-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0068_event_programming_status_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='target_month',
            field=models.DateField(blank=True, help_text='For undated proposals: the rough month being targeted. Always stored as the 1st of the month. Shown in the diary alongside monthly ideas notes.', null=True, verbose_name='Target month'),
        ),
        migrations.AlterField(
            model_name='event',
            name='programming_notes',
            field=models.TextField(blank=True, help_text="Internal working notes — not visible to the public. Use for queue context (e.g. 'looking for a Friday in May — sample date'), meeting decisions, and conditions attached to approval. Financial details and hire contacts belong in Terms.", verbose_name="Programmer's notes"),
        ),
    ]
