# Generated by Django 5.2.14 on 2026-06-10 09:01

from django.db import migrations, models

_BBFC_DEFAULTS = [
    {"value": "U",   "label": "U — Universal"},
    {"value": "PG",  "label": "PG — Parental Guidance"},
    {"value": "12A", "label": "12A — Cinema only, under 12s with adult"},
    {"value": "12",  "label": "12"},
    {"value": "15",  "label": "15"},
    {"value": "18",  "label": "18"},
]


def seed_bbfc_defaults(apps, schema_editor):
    SiteConfiguration = apps.get_model("diary", "SiteConfiguration")
    SiteConfiguration.objects.filter(age_rating_choices=[]).update(
        age_rating_choices=_BBFC_DEFAULTS
    )


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0069_event_target_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='age_rating_choices',
            field=models.JSONField(blank=True, default=list, help_text='Age-rating options shown in the event edit form. A JSON list of {"value": "...", "label": "..."} objects, e.g. BBFC: U / PG / 12A / 12 / 15 / 18. Leave empty to hide the age restriction field.'),
        ),
        migrations.RunPython(seed_bbfc_defaults, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='event',
            name='age_restriction',
            field=models.CharField(blank=True, default='', help_text='Age rating or restriction for this event. Options are configured in the site settings.', max_length=32, verbose_name='Age restriction'),
        ),
    ]
