# Generated by Django 5.2.14 on 2026-06-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0071_siteconfiguration_ticket_link_guidance_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='age_rating_choices',
            field=models.JSONField(blank=True, default=list, help_text='Age-rating options shown in the event edit form. e.g. BBFC: U / PG / 12A / 12 / 15 / 18. Leave the list empty to hide the age restriction field entirely.'),
        ),
    ]
