# Generated by Django 5.2.14 on 2026-06-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0072_alter_siteconfiguration_age_rating_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='stats_label',
            field=models.CharField(blank=True, default='', help_text="Optional label used to group this role with others in volunteer stats. E.g. set 'Bar' on 'Bar Staff - Shift 1' and 'Bar Staff - Shift 2' so they appear as a single 'Bar' row. Leave blank to use the role name.", max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='programming_min_event_shifts',
            field=models.PositiveSmallIntegerField(default=10, help_text='Informal threshold: minimum confirmed non-training shifts before a volunteer is considered eligible to programme their own event. Shown on the volunteer stats page as informational context (never enforced in code).'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='stats_training_tag_slugs',
            field=models.JSONField(default=list, help_text='Tag slugs whose events are excluded from the \'event shifts\' count on the volunteer stats page (e.g. inductions and training sessions). JSON list of strings, e.g. ["induction", "training-for-volunteers"].'),
        ),
    ]
