# Generated by Django 5.2.14 on 2026-06-11 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0073_role_stats_label_and_siteconfiguration_stats_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stats_training_tag_slugs',
            field=models.JSONField(blank=True, default=list, help_text='Tag slugs whose events are excluded from the \'event shifts\' count on the volunteer stats page (e.g. inductions and training sessions). JSON list of strings, e.g. ["induction", "training-for-volunteers"].'),
        ),
    ]
