# Generated by Django 5.2.14 on 2026-06-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0076_siteconfiguration_tmdb_api_key_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost_distributor',
            field=models.CharField(blank=True, help_text='The distribution company or booker contact (film licence / performer fee).', max_length=256, null=True, verbose_name='Distributor / booker'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_fee_includes_vat',
            field=models.BooleanField(blank=True, null=True, verbose_name='Fee includes VAT'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_flat_fee_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed licence or performance fee in pounds.', max_digits=8, null=True, verbose_name='Flat fee (£)'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_minimum_guarantee_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Guaranteed minimum payment regardless of door takings.', max_digits=8, null=True, verbose_name='Minimum guarantee (£)'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_percentage_split',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of net door takings paid to the distributor/performer.', max_digits=5, null=True, verbose_name='% split to distributor'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_total_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total agreed fee (performer / hire).', max_digits=8, null=True, verbose_name='Total cost (£)'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_type',
            field=models.CharField(blank=True, choices=[('film_license', 'Film licence'), ('performer_fee', 'Performer fee / gig'), ('venue_hire', 'Venue hire'), ('internal', 'Internal / volunteer'), ('tbc', 'TBC')], help_text='The nature of the financial deal for this event.', max_length=32, null=True, verbose_name='Cost type'),
        ),
        migrations.AddField(
            model_name='event',
            name='technical_notes',
            field=models.TextField(blank=True, help_text="AV / tech rider requirements, projection format, sound spec, etc. Kept separate from financial terms so the two don't get conflated.", max_length=4096, null=True, verbose_name='Technical notes'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cost_distributor',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Distributor / booker'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cost_fee_includes_vat',
            field=models.BooleanField(blank=True, null=True, verbose_name='Fee includes VAT'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cost_flat_fee_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Flat fee (£)'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cost_minimum_guarantee_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Minimum guarantee (£)'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cost_percentage_split',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='% split to distributor'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cost_total_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total cost (£)'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cost_type',
            field=models.CharField(blank=True, choices=[('film_license', 'Film licence'), ('performer_fee', 'Performer fee / gig'), ('venue_hire', 'Venue hire'), ('internal', 'Internal / volunteer'), ('tbc', 'TBC')], max_length=32, null=True, verbose_name='Cost type'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='structured_cost_terms_enabled',
            field=models.BooleanField(default=False, help_text='Enable structured cost fields (cost type, flat fee, % split, etc.) on event edit forms. When on, programmers can record the deal type directly rather than free-texting it into Terms. The Terms textarea remains available for unusual arrangements and legacy records.'),
        ),
        migrations.AlterField(
            model_name='film',
            name='tmdb_certificate',
            field=models.CharField(blank=True, help_text='UK certificate as returned by TMDB. For reference — the canonical public-facing cert is set separately on the event.', max_length=16, verbose_name='Certificate (TMDB)'),
        ),
    ]
