# Generated by Django 5.2.14 on 2026-06-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0077_event_cost_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='structured_cost_required',
            field=models.BooleanField(default=False, help_text='Require cost type to be set (to something other than TBC) before any showing can be confirmed. Only takes effect when structured cost terms are enabled above. When cost type is set, the terms word-count check is automatically waived; TBC still falls back to the terms word-count check.'),
        ),
    ]
