# Generated by Django 5.2.14 on 2026-06-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0078_siteconfiguration_structured_cost_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='last_gasp_cooldown_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='How many days must pass before a second last-gasp email can be sent to the same volunteer.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='last_gasp_email_body',
            field=models.TextField(blank=True, help_text="Body of the last-gasp email. Use {name} for the volunteer's name and {venue} for the venue name. Leave blank to disable sending."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='last_gasp_email_subject',
            field=models.CharField(blank=True, help_text="Subject line for the last-gasp re-engagement email. Use {name} for the volunteer's name and {venue} for the venue name.", max_length=200),
        ),
    ]
