# Generated by Django 5.2.14 on 2026-06-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0082_siteconfiguration_suspension_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='tmdb_certificate',
        ),
        migrations.RemoveField(
            model_name='film',
            name='tmdb_fetched_at',
        ),
        migrations.RemoveField(
            model_name='film',
            name='tmdb_id',
        ),
        migrations.RemoveField(
            model_name='film',
            name='tmdb_poster_path',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='tmdb_api_key',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='tmdb_api_key_email',
        ),
        migrations.AddField(
            model_name='film',
            name='poster_url',
            field=models.CharField(blank=True, help_text='Direct URL to a poster image. Set automatically from OMDb.', max_length=512, verbose_name='Poster URL'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='certificate_lookup_url',
            field=models.CharField(blank=True, default='https://www.bbfc.co.uk/search?q={title}', help_text="URL template for looking up a film's certificate. Use {title} and {year} as placeholders — they will be URL-encoded and substituted when the link is generated. Example (BBFC): https://www.bbfc.co.uk/search?q={title} Leave blank to hide the lookup link.", max_length=512, verbose_name='Certificate lookup URL'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='omdb_api_key',
            field=models.CharField(blank=True, default='', help_text='API key for the Open Movie Database (OMDb). Used for film search and metadata import. Get a free key at https://www.omdbapi.com/apikey.aspx. If set here, this takes precedence over the OMDB_API_KEY environment variable.', max_length=256, verbose_name='OMDb API key'),
        ),
        migrations.AlterField(
            model_name='film',
            name='overview',
            field=models.TextField(blank=True, help_text='Plot summary. Internal reference only — not shown publicly.'),
        ),
    ]
