# Generated by Django 5.2.14 on 2026-06-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0083_omdb_replace_tmdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost_rider_notes',
            field=models.TextField(blank=True, help_text='Food, drink, accommodation, or other rider requirements for the performer or hirer.', max_length=4096, null=True, verbose_name='Hospitality / rider'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_sound_engineer_fee_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sound engineer fee (£)'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_sound_engineer_name',
            field=models.CharField(blank=True, help_text='Name or contact for the sound engineer, if applicable.', max_length=256, null=True, verbose_name='Sound engineer'),
        ),
        migrations.AddField(
            model_name='event',
            name='cost_sound_engineer_paid_by',
            field=models.CharField(blank=True, choices=[('venue', 'Venue'), ('performer', 'Performer'), ('hirer', 'Hirer')], max_length=16, null=True, verbose_name='Sound engineer paid by'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cost_rider_notes',
            field=models.TextField(blank=True, max_length=4096, null=True, verbose_name='Hospitality / rider'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cost_sound_engineer_fee_gbp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Sound engineer fee (£)'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cost_sound_engineer_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Sound engineer'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='cost_sound_engineer_paid_by',
            field=models.CharField(blank=True, choices=[('venue', 'Venue'), ('performer', 'Performer'), ('hirer', 'Hirer')], max_length=16, null=True, verbose_name='Sound engineer paid by'),
        ),
    ]
