# Generated by Django 5.2.14 on 2026-06-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0085_role_is_one_shot'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='perm_diary_calendar',
            field=models.CharField(choices=[('volunteer', 'All volunteers'), ('programmer', 'Programmer+'), ('panopticon', 'Panopticon only')], default='programmer', help_text='Who can access the calendar edit view.', max_length=12, verbose_name='Diary — calendar'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='perm_diary_edit',
            field=models.CharField(choices=[('volunteer', 'All volunteers'), ('programmer', 'Programmer+'), ('panopticon', 'Panopticon only')], default='programmer', help_text='Who can access the diary editing list.', max_length=12, verbose_name='Diary — edit list'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='perm_diary_reports',
            field=models.CharField(choices=[('volunteer', 'All volunteers'), ('programmer', 'Programmer+'), ('panopticon', 'Panopticon only')], default='programmer', help_text='Who can access copy, terms, and text reports.', max_length=12, verbose_name='Diary — reports'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='perm_donations_manage',
            field=models.CharField(choices=[('volunteer', 'All volunteers'), ('programmer', 'Programmer+'), ('panopticon', 'Panopticon only')], default='programmer', help_text='Who can access the donations management page.', max_length=12, verbose_name='Website — donations manage'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='perm_event_tags',
            field=models.CharField(choices=[('volunteer', 'All volunteers'), ('programmer', 'Programmer+'), ('panopticon', 'Panopticon only')], default='programmer', help_text='Who can edit event tags.', max_length=12, verbose_name='Diary — event tags'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='perm_event_templates',
            field=models.CharField(choices=[('volunteer', 'All volunteers'), ('programmer', 'Programmer+'), ('panopticon', 'Panopticon only')], default='programmer', help_text='Who can access event templates (list and detail). Template import always requires Panopticon.', max_length=12, verbose_name='Diary — event templates'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='perm_printed_programmes',
            field=models.CharField(choices=[('volunteer', 'All volunteers'), ('programmer', 'Programmer+'), ('panopticon', 'Panopticon only')], default='programmer', help_text='Who can upload printed programmes.', max_length=12, verbose_name='Diary — printed programmes'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='perm_programming_queue',
            field=models.CharField(choices=[('volunteer', 'All volunteers'), ('programmer', 'Programmer+'), ('panopticon', 'Panopticon only')], default='programmer', help_text='Who can access the programming queue.', max_length=12, verbose_name='Diary — programming queue'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='perm_roles',
            field=models.CharField(choices=[('volunteer', 'All volunteers'), ('programmer', 'Programmer+'), ('panopticon', 'Panopticon only')], default='programmer', help_text='Who can edit rota roles.', max_length=12, verbose_name='Diary — roles'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='perm_rooms',
            field=models.CharField(choices=[('volunteer', 'All volunteers'), ('programmer', 'Programmer+'), ('panopticon', 'Panopticon only')], default='programmer', help_text='Who can edit rooms.', max_length=12, verbose_name='Diary — rooms'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='perm_rota_vacancies',
            field=models.CharField(choices=[('volunteer', 'All volunteers'), ('programmer', 'Programmer+'), ('panopticon', 'Panopticon only')], default='volunteer', help_text='Who can see the rota vacancies page.', max_length=12, verbose_name='Rota — vacancies page'),
        ),
    ]
