# Generated by Django 5.2.14 on 2026-06-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0087_diary_read_write_perm_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='film_programming_guide_url',
            field=models.URLField(blank=True, default='', help_text='URL linked at the bottom of the ticket link setup guide panel on the event edit form. Typically a full guide to your ticketing platform. Leave blank to omit the link.', verbose_name='Film programming guide URL'),
        ),
    ]
