# Generated by Django 5.2.14 on 2026-06-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0088_siteconfiguration_film_programming_guide_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='stats_programming_note',
            field=models.TextField(blank=True, default='', help_text='Optional extra text shown below the programming eligibility count on the volunteer stats page. Plain text only. Leave blank to show nothing.', verbose_name='Programming eligibility note'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='programming_min_event_shifts',
            field=models.PositiveSmallIntegerField(default=10, help_text='Minimum confirmed non-training shifts before a volunteer is considered ready to programme their own event. Shown on the volunteer stats page as a target — never enforced by the system.', verbose_name='Programming eligibility threshold'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='stats_training_tag_slugs',
            field=models.JSONField(blank=True, default=list, help_text="Events tagged with any of these are excluded from a volunteer's confirmed shift count on the stats page. Use this to separate training and induction sessions from regular programming activity.", verbose_name='Tags excluded from shift count'),
        ),
    ]
