# Generated by Django 5.2.14 on 2026-06-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0089_add_stats_programming_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='last_gasp_email_enabled',
            field=models.BooleanField(default=False, help_text='A last-gasp email is a final, optional re-engagement message sent to a volunteer before their account is anonymised or deleted under data-retention rules — a courtesy “we’re about to remove your data, here’s a chance to come back” note. When enabled, the pool health page shows a button to send one to each purge candidate. (The email-address export, for sending outside the toolkit, is always available regardless of this setting.)', verbose_name='Enable last-gasp email features'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='last_gasp_email_body',
            field=models.TextField(blank=True, help_text="Body text. Use {name} for the volunteer's name and {venue} for the venue name. Can be left blank even when the feature is enabled — the compose page will still open so you can write a message from scratch each time."),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='last_gasp_email_subject',
            field=models.CharField(blank=True, help_text="Subject line. Use {name} for the volunteer's name and {venue} for the venue name.", max_length=200),
        ),
    ]
