# Generated by Django 5.2.14 on 2026-06-28 13:04

import datetime
import django.db.migrations.operations.special
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# toolkit.members.migrations.0012_volunteer_status
# toolkit.members.migrations.0015_split_dir_share_name


def populate_status_from_active(apps, schema_editor):
    Volunteer = apps.get_model("members", "Volunteer")
    Volunteer.objects.filter(active=False).update(status="retired")
    # active=True rows already default to 'active'


def split_dir_share_name(apps, schema_editor):
    Volunteer = apps.get_model("members", "Volunteer")
    # Map old enum -> (listed, style). Anything other than "none" means listed.
    for vol in Volunteer.objects.all():
        old = getattr(vol, "dir_share_name", "none") or "none"
        vol.dir_share_listed = old != "none"
        vol.dir_share_name_style = "initial" if old == "initial" else "full"
        vol.save(update_fields=["dir_share_listed", "dir_share_name_style"])


def recombine_dir_share_name(apps, schema_editor):
    Volunteer = apps.get_model("members", "Volunteer")
    for vol in Volunteer.objects.all():
        if not vol.dir_share_listed:
            vol.dir_share_name = "none"
        else:
            vol.dir_share_name = vol.dir_share_name_style or "full"
        vol.save(update_fields=["dir_share_name"])


class Migration(migrations.Migration):

    # MariaDB doesn't allow schema changes inside a transaction with data
    # migrations (inherited from 0015_split_dir_share_name). The squashed
    # migration interleaves AddField/RemoveField with RunPython, so keep it
    # non-atomic.
    atomic = False

    replaces = [
        ("members", "0009_volunteer_user"),
        ("members", "0010_make_email_mandatory"),
        ("members", "0011_anonymisation_log"),
        ("members", "0012_volunteer_status"),
        ("members", "0013_volunteer_login_inactive"),
        ("members", "0014_volunteer_directory_fields"),
        ("members", "0015_split_dir_share_name"),
        ("members", "0016_panopticon_programmer_grants"),
        ("members", "0017_volunteer_digest_fields"),
        ("members", "0018_remove_volunteer_active"),
        ("members", "0019_volunteer_status_suspended"),
        ("members", "0020_remove_volunteer_login_inactive"),
        ("members", "0021_volunteer_status_anonymised"),
        ("members", "0022_qualification_volunteerqualification"),
        ("members", "0023_rename_qualification_grant_fields"),
        ("members", "0024_exportauditlog"),
        ("members", "0025_volunteer_retention_exempt_and_last_gasp_log"),
        ("members", "0026_exportauditlog_export_reason"),
        ("members", "0027_volunteer_dashboard_and_diary_prefs"),
        ("members", "0028_volunteer_suspension_reason"),
    ]

    dependencies = [
        ("labs", "0001_initial_v2"),
        (
            "members",
            "0008_member_preferred_pronouns_squashed_0009_auto_20220627_1114",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="user",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=64),
        ),
        migrations.CreateModel(
            name="AnonymisationLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volunteer_pk", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "AnonymisationLog",
            },
        ),
        migrations.AddField(
            model_name="volunteer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("dormant", "Dormant"),
                    ("retired", "Retired"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            code=populate_status_from_active,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name="volunteer",
            name="login_inactive",
            field=models.BooleanField(
                default=False,
                help_text="Flagged by the auto-dormancy check: this volunteer has not logged in recently. Cleared manually after follow-up.",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="access_intro",
            field=models.TextField(
                blank=True,
                help_text="A sentence or two about yourself for context (optional).",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="access_links",
            field=models.TextField(
                blank=True,
                help_text="Links to further information about your access needs (optional).",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="access_needs",
            field=models.TextField(
                blank=True,
                help_text="What you need to participate in shifts and events at the venue.",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="collectives",
            field=models.ManyToManyField(
                blank=True, related_name="volunteers", to="labs.collective"
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="dir_share_access_rider",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="dir_share_collectives",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="dir_share_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="dir_share_name",
            field=models.CharField(
                choices=[
                    ("full", "Full name"),
                    ("initial", "First name + initial"),
                    ("none", "Not listed"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="dir_share_phone",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="dir_share_pronouns",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="emergency_contact_name",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="emergency_contact_relationship",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="dir_share_listed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="dir_share_name_style",
            field=models.CharField(
                choices=[
                    ("full", "Full name"),
                    ("initial", "First name + initial"),
                ],
                default="full",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            code=split_dir_share_name,
            reverse_code=recombine_dir_share_name,
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="dir_share_name",
        ),
        migrations.CreateModel(
            name="PanopticonGrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Why does this person have Panopticon access?"
                    ),
                ),
                ("granted_at", models.DateField(auto_now_add=True)),
                ("last_reviewed_at", models.DateField(blank=True, null=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="panopticon_grant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "PanopticonGrant",
                "ordering": ["granted_at"],
            },
        ),
        migrations.CreateModel(
            name="ProgrammerGrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_at", models.DateField(auto_now_add=True)),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmer_grant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ProgrammerGrant",
                "ordering": ["user__username"],
            },
        ),
        migrations.AddField(
            model_name="volunteer",
            name="last_digest_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set automatically after each digest send. Used to compute the 'new on programme' lookback window.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="weekly_digest",
            field=models.BooleanField(
                default=False,
                help_text="Send a weekly email summary of upcoming shifts, new programme items, and starred events.",
            ),
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="active",
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="login_inactive",
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("dormant", "Dormant"),
                    ("retired", "Retired"),
                    ("suspended", "Suspended"),
                    ("anonymised", "Anonymised"),
                ],
                default="active",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal notes: what this covers, who can award it, etc.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="volunteer",
            name="roles",
        ),
        migrations.CreateModel(
            name="VolunteerQualification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("granted_on", models.DateField(default=datetime.date.today)),
                (
                    "granted_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name of the person who recorded this (leave blank if self-recorded).",
                        max_length=128,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "qualification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holders",
                        to="members.qualification",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualifications",
                        to="members.volunteer",
                    ),
                ),
            ],
            options={
                "ordering": ["qualification__name"],
                "unique_together": {("volunteer", "qualification")},
            },
        ),
        migrations.AddField(
            model_name="volunteer",
            name="retention_exempt",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="retention_exempt_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name="LastGaspEmailLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="last_gasp_emails",
                        to="members.volunteer",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportAuditLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exported_at", models.DateTimeField(auto_now_add=True)),
                ("fields_included", models.JSONField(default=list)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                (
                    "exported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "export_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "ordering": ["-exported_at"],
            },
        ),
        migrations.AddField(
            model_name="volunteer",
            name="dashboard_card_order",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of dashboard card IDs, as set by the user's drag-to-reorder.",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="dashboard_hidden_cards",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Dashboard card IDs the user has hidden (e.g. 'dash_unconfirmed').",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="diary_days_ahead",
            field=models.IntegerField(
                default=365,
                help_text="Days ahead shown in the diary edit list. Set when the user selects a range.",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="favourite_link_keys",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ordered list of link catalogue keys pinned to the dashboard favourites panel.",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="suspension_reason",
            field=models.TextField(blank=True),
        ),
    ]
