# Generated by Django 5.2.11 on 2026-02-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0009_volunteer_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(max_length=64),
        ),
    ]
