# Generated by Django 5.2.14 on 2026-07-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportauditlog',
            name='filter_event_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='exportauditlog',
            name='filter_type',
            field=models.CharField(choices=[('all', 'All volunteers'), ('upcoming', 'Volunteers with any upcoming shift'), ('events', 'Volunteers signed up to specific events')], default='all', max_length=20),
        ),
    ]
