# Generated by Django 5.2.14 on 2026-05-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0009_areaphoto'),
        ('members', '0013_volunteer_login_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='access_intro',
            field=models.TextField(blank=True, help_text='A sentence or two about yourself for context (optional).', max_length=500),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='access_links',
            field=models.TextField(blank=True, help_text='Links to further information about your access needs (optional).', max_length=500),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='access_needs',
            field=models.TextField(blank=True, help_text='What you need to participate in shifts and events at the venue.'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='collectives',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='labs.collective'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='dir_share_access_rider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='dir_share_collectives',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='dir_share_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='dir_share_name',
            field=models.CharField(choices=[('full', 'Full name'), ('initial', 'First name + initial'), ('none', 'Not listed')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='dir_share_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='dir_share_pronouns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
