# Generated by Django 5.2.14 on 2026-05-25 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_split_dir_share_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanopticonGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why does this person have Panopticon access?')),
                ('granted_at', models.DateField(auto_now_add=True)),
                ('last_reviewed_at', models.DateField(blank=True, null=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panopticon_grant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PanopticonGrant',
                'ordering': ['granted_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammerGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programmer_grant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ProgrammerGrant',
                'ordering': ['user__username'],
            },
        ),
    ]
