# Generated by Django 5.2.14 on 2026-05-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_panopticon_programmer_grants'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='last_digest_sent_at',
            field=models.DateTimeField(blank=True, help_text="Set automatically after each digest send. Used to compute the 'new on programme' lookback window.", null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='weekly_digest',
            field=models.BooleanField(default=False, help_text='Send a weekly email summary of upcoming shifts, new programme items, and starred events.'),
        ),
    ]
