# Generated by Django 5.2.14 on 2026-05-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_volunteer_digest_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='active',
        ),
    ]
