# Generated by Django 5.2.14 on 2026-05-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_volunteer_status_suspended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='login_inactive',
        ),
    ]
