# Generated by Django 5.2.14 on 2026-05-31 12:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_volunteer_status_anonymised'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Internal notes: what this covers, who can award it, etc.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='roles',
        ),
        migrations.CreateModel(
            name='VolunteerQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_on', models.DateField(default=datetime.date.today)),
                ('awarded_by', models.CharField(blank=True, default='', help_text='Name of the person who awarded this (leave blank if self-recorded).', max_length=128)),
                ('notes', models.TextField(blank=True, default='')),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='members.qualification')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='members.volunteer')),
            ],
            options={
                'ordering': ['qualification__name'],
                'unique_together': {('volunteer', 'qualification')},
            },
        ),
    ]
