# Generated by Django 5.2.14 on 2026-06-11 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_exportauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='retention_exempt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='retention_exempt_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='LastGaspEmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_gasp_emails', to='members.volunteer')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
