# Generated by Django 5.2.14 on 2026-06-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_exportauditlog_export_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='dashboard_card_order',
            field=models.JSONField(blank=True, default=list, help_text="Ordered list of dashboard card IDs, as set by the user's drag-to-reorder."),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='dashboard_hidden_cards',
            field=models.JSONField(blank=True, default=list, help_text="Dashboard card IDs the user has hidden (e.g. 'dash_unconfirmed')."),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='diary_days_ahead',
            field=models.IntegerField(default=365, help_text='Days ahead shown in the diary edit list. Set when the user selects a range.'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='favourite_link_keys',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of link catalogue keys pinned to the dashboard favourites panel.'),
        ),
    ]
