# Generated by Django 5.2.14 on 2026-06-11 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diary', '0072_alter_siteconfiguration_age_rating_choices'),
        ('members', '0024_exportauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InductionsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inductions_enabled', models.BooleanField(default=False, help_text='Enable the inductions sign-up workflow. When off, all public induction URLs return 404.')),
                ('induction_purge_days', models.PositiveIntegerField(default=7, help_text='Days after a session date before pending/no-show sign-ups are automatically purged.')),
                ('confirmation_email_subject', models.CharField(blank=True, help_text='Leave blank to use the default. Variables: {name} {venue} {session_title}', max_length=200)),
                ('confirmation_email_body', models.TextField(blank=True, help_text='Leave blank to use the default. Variables: {name} {venue} {session_title} {session_date} {session_location} {calendar_url}')),
                ('reminder_email_subject', models.CharField(blank=True, help_text='Leave blank to use the default.', max_length=200)),
                ('reminder_email_body', models.TextField(blank=True)),
                ('welcome_email_subject', models.CharField(blank=True, help_text='Leave blank to use the default. Variables: {name} {venue} {session_title} {validity} {password_url}', max_length=200)),
                ('welcome_email_body', models.TextField(blank=True)),
                ('access_needs_ack_subject', models.CharField(blank=True, max_length=200)),
                ('access_needs_ack_body', models.TextField(blank=True)),
                ('welcome_pack_url', models.CharField(blank=True, help_text='URL to a welcome pack document included in the welcome email.', max_length=500)),
                ('welcome_pack_label', models.CharField(default='Welcome pack', help_text='Link text for the welcome pack URL.', max_length=100)),
                ('organiser_notification_email', models.EmailField(blank=True, help_text='Email address that receives a notification when a new access needs request is submitted.', max_length=254)),
            ],
            options={
                'verbose_name': 'Inductions settings',
                'verbose_name_plural': 'Inductions settings',
                'db_table': 'InductionsSettings',
            },
        ),
        migrations.CreateModel(
            name='InductionSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('session_type', models.CharField(choices=[('regular', 'Regular (cinema)'), ('small_group', 'Small group (meeting room / venue)'), ('one_to_one', '1:1 (access needs)')], default='regular', max_length=20)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('custom_questions', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('purged', 'Purged')], default='open', max_length=10)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('purge_after', models.DateTimeField()),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_induction_sessions', to=settings.AUTH_USER_MODEL)),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='induction_sessions', to='diary.event')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InductionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('access_needs', models.TextField()),
                ('rough_availability', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('declined', 'Declined'), ('purged', 'Purged')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('purge_after', models.DateTimeField()),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='induction_request', to='members.volunteer')),
                ('linked_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='inductions.inductionsession')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='InductionSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('custom_responses', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checked_in', 'Checked in'), ('no_show', 'No show')], default='pending', max_length=20)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_signups', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='inductions.inductionsession')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='induction_signups', to='members.volunteer')),
            ],
            options={
                'ordering': ['signed_up_at'],
            },
        ),
    ]
