# Generated by Django 5.2.14 on 2026-06-28 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("inductions", "0001_initial"),
        ("inductions", "0002_inductionsignup_desired_username"),
        ("inductions", "0003_session_capacity_and_notification_settings"),
        ("inductions", "0004_inductionssettings_default_max_signups"),
        ("inductions", "0005_inductionssettings_access_needs_and_privacy"),
        ("inductions", "0006_inductionssettings_access_needs_enabled"),
        ("inductions", "0007_inductionsignup_phone_address_postcode"),
        ("inductions", "0008_drop_linked_event"),
        ("inductions", "0009_alter_inductionsession_session_type"),
    ]

    initial = True

    dependencies = [
        ("diary", "0072_alter_siteconfiguration_age_rating_choices"),
        ("members", "0024_exportauditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InductionSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("small_group", "Small group"),
                            ("one_to_one", "1:1 (access needs)"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "custom_questions",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("purged", "Purged"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("purge_after", models.DateTimeField()),
                (
                    "reminder_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_induction_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "max_signups",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum sign-ups for this session. Leave blank to use the site default (set in Inductions settings), or leave both blank for no cap.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="InductionRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("access_needs", models.TextField()),
                ("rough_availability", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("contacted", "Contacted"),
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                            ("purged", "Purged"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("contacted_at", models.DateTimeField(blank=True, null=True)),
                ("purge_after", models.DateTimeField()),
                (
                    "volunteer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="induction_request",
                        to="members.volunteer",
                    ),
                ),
                (
                    "linked_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_requests",
                        to="inductions.inductionsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="InductionSignup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "custom_responses",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("checked_in", "Checked in"),
                            ("no_show", "No show"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("signed_up_at", models.DateTimeField(auto_now_add=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_in_signups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signups",
                        to="inductions.inductionsession",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="induction_signups",
                        to="members.volunteer",
                    ),
                ),
                (
                    "desired_username",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="If set, used as the volunteer's login username instead of auto-generating from name.",
                        max_length=150,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("address", models.CharField(blank=True, max_length=128)),
                ("postcode", models.CharField(blank=True, max_length=16)),
            ],
            options={
                "ordering": ["signed_up_at"],
            },
        ),
        migrations.CreateModel(
            name="InductionsSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inductions_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable the inductions sign-up workflow. When off, all public induction URLs return 404. If you're handling inductions sign-ups through another route (e.g. Google Forms) then you'll want to leave this unchecked.",
                    ),
                ),
                (
                    "induction_purge_days",
                    models.PositiveIntegerField(
                        default=7,
                        help_text="Days after a session date before pending/no-show sign-ups are automatically purged.",
                    ),
                ),
                (
                    "confirmation_email_subject",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the default. Variables: {name} {venue} {session_title}",
                        max_length=200,
                    ),
                ),
                (
                    "confirmation_email_body",
                    models.TextField(
                        blank=True,
                        help_text="Leave blank to use the default. Variables: {name} {venue} {session_title} {session_date} {session_location} {calendar_url}",
                    ),
                ),
                (
                    "reminder_email_subject",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the default.",
                        max_length=200,
                    ),
                ),
                ("reminder_email_body", models.TextField(blank=True)),
                (
                    "welcome_email_subject",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to use the default. Variables: {name} {username} {venue} {session_title} {validity} {password_url} {password_reset_url}",
                        max_length=200,
                    ),
                ),
                ("welcome_email_body", models.TextField(blank=True)),
                (
                    "access_needs_ack_subject",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Access needs acknowledgement subject",
                    ),
                ),
                (
                    "access_needs_ack_body",
                    models.TextField(
                        blank=True,
                        verbose_name="Access needs acknowledgement body",
                    ),
                ),
                (
                    "welcome_pack_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to a welcome pack document included in the welcome email.",
                        max_length=500,
                    ),
                ),
                (
                    "welcome_pack_label",
                    models.CharField(
                        default="Welcome pack",
                        help_text="Link text for the welcome pack URL.",
                        max_length=100,
                    ),
                ),
                (
                    "organiser_notification_email",
                    models.EmailField(
                        default="inductions@example.com",
                        help_text="Email address that receives organiser notifications (new 1:1 request, session full, etc.). Set this to a real address before going live.",
                        max_length=254,
                    ),
                ),
                (
                    "notify_on_each_signup",
                    models.BooleanField(
                        default=False,
                        help_text="Also send a notification for every new sign-up, not just when a session reaches capacity. Useful for small or closely-watched sessions.",
                    ),
                ),
                (
                    "default_max_signups",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Default maximum sign-ups for group induction sessions. Leave blank for no site-wide cap. Individual sessions can override this with their own limit.",
                        null=True,
                    ),
                ),
                (
                    "privacy_policy_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to your GDPR/privacy policy. Linked from the sign-up consent checkbox. Leave blank to omit the link.",
                        max_length=500,
                    ),
                ),
                (
                    "access_needs_intro_text",
                    models.TextField(
                        blank=True,
                        help_text="Introductory paragraph on the 1:1 induction request form. Leave blank to use the default text.",
                    ),
                ),
                (
                    "access_needs_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable the 1:1 induction request page. Uncheck to hide it — useful if you don't currently offer 1:1 inductions.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inductions settings",
                "verbose_name_plural": "Inductions settings",
                "db_table": "InductionsSettings",
            },
        ),
    ]
