# Generated by Django 5.2.14 on 2026-07-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductions', '0001_initial_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionssettings',
            name='consent_renewal_days',
            field=models.PositiveIntegerField(default=365, help_text="Days after a volunteer's last consent before they're asked to reconfirm it. 0 disables renewal reminders."),
        ),
        migrations.AddField(
            model_name='inductionssettings',
            name='consent_renewal_grace_days',
            field=models.PositiveIntegerField(default=30, help_text='Days after a renewal reminder is sent before the volunteer is flagged as consent-overdue for manual review.'),
        ),
        migrations.AddField(
            model_name='inductionssettings',
            name='privacy_policy_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the privacy policy was last marked as updated.', null=True),
        ),
        migrations.AddField(
            model_name='inductionssettings',
            name='privacy_policy_version',
            field=models.PositiveIntegerField(default=1, help_text='Bumped automatically when the policy is marked as updated. Volunteers who last consented to an earlier version are flagged for renewal and emailed immediately.'),
        ),
    ]
