# Generated by Django 5.2.14 on 2026-07-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductions', '0002_inductionssettings_consent_renewal_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inductionssettings',
            name='consent_renewal_days',
        ),
        migrations.RemoveField(
            model_name='inductionssettings',
            name='consent_renewal_grace_days',
        ),
    ]
