# Generated by Django 5.2.14 on 2026-07-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductions', '0003_remove_inductionssettings_consent_renewal_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductionsession',
            name='max_signups',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum sign-ups for this session. Leave blank for unlimited sign-ups.', null=True),
        ),
        migrations.AlterField(
            model_name='inductionsession',
            name='purge_after',
            field=models.DateTimeField(help_text="Personal details (name, email, and answers) for anyone still pending or marked no-show are automatically deleted after this date, and the session is marked 'Purged'. Sign-ups who were checked in and already have a volunteer account are not affected. Runs automatically once a day — defaults to the session date plus the site-wide purge window (set in Inductions settings)."),
        ),
        migrations.AlterField(
            model_name='inductionsignup',
            name='desired_username',
            field=models.CharField(blank=True, help_text="If set, used as the volunteer's login username instead of auto-generating from name.", max_length=150),
        ),
        migrations.AlterField(
            model_name='inductionssettings',
            name='default_max_signups',
            field=models.PositiveIntegerField(blank=True, help_text="Suggested starting value for the 'maximum sign-ups' field when creating a new induction session — each session's own cap can then be adjusted or cleared independently. Leave blank to suggest no cap.", null=True),
        ),
    ]
