# Generated by Django 5.2.14 on 2026-06-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductions', '0005_inductionssettings_access_needs_and_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductionssettings',
            name='access_needs_enabled',
            field=models.BooleanField(default=True, help_text="Enable the 1:1 induction request page. Uncheck to hide it — useful if you don't currently offer 1:1 inductions."),
        ),
        migrations.AlterField(
            model_name='inductionsession',
            name='max_signups',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum sign-ups for this session. Leave blank to use the site default (set in Inductions settings), or leave both blank for no cap.', null=True),
        ),
        migrations.AlterField(
            model_name='inductionssettings',
            name='access_needs_ack_body',
            field=models.TextField(blank=True, verbose_name='Access needs acknowledgement body'),
        ),
        migrations.AlterField(
            model_name='inductionssettings',
            name='access_needs_ack_subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='Access needs acknowledgement subject'),
        ),
        migrations.AlterField(
            model_name='inductionssettings',
            name='inductions_enabled',
            field=models.BooleanField(default=False, help_text="Enable the inductions sign-up workflow. When off, all public induction URLs return 404. If you're handling inductions sign-ups through another route (e.g. Google Forms) then you'll want to leave this unchecked."),
        ),
    ]
