# Generated by Django 5.2.14 on 2026-06-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductions', '0007_inductionsignup_phone_address_postcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inductionsession',
            name='linked_event',
        ),
        migrations.AlterField(
            model_name='inductionssettings',
            name='welcome_email_subject',
            field=models.CharField(blank=True, help_text='Leave blank to use the default. Variables: {name} {username} {venue} {session_title} {validity} {password_url} {password_reset_url}', max_length=200),
        ),
    ]
