# Generated by Django 5.2.14 on 2026-06-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inductions', '0008_drop_linked_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductionsession',
            name='session_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('small_group', 'Small group'), ('one_to_one', '1:1 (access needs)')], default='regular', max_length=20),
        ),
    ]
