# Generated by Django 5.2.14 on 2026-07-14 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipients', models.TextField(help_text='Comma-joined; usually one address')),
                ('subject', models.CharField(max_length=255)),
                ('success', models.BooleanField()),
                ('error', models.TextField(blank=True)),
                ('backend', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model', models.CharField(max_length=64)),
                ('object_pk', models.CharField(max_length=64)),
                ('description', models.TextField(help_text="The object's str() plus key context, e.g. event name and showing date")),
                ('via', models.CharField(choices=[('edit-ui', 'Edit UI'), ('management-command', 'Management command'), ('cascade', 'Cascade'), ('signal', 'Signal (unexpected path)')], max_length=32)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
