# Generated by Django 5.2.14 on 2026-07-14 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemaillog',
            name='trigger_source',
            field=models.CharField(blank=True, help_text="What set this send off, e.g. 'Web request', 'Scheduled job: send_volunteer_digest', 'Mailout job #42'", max_length=255),
        ),
        migrations.AddField(
            model_name='sentemaillog',
            name='triggered_by',
            field=models.ForeignKey(blank=True, help_text='The logged-in user whose action caused this send, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
